### ISSUE TITLE
To be able to copy a commit message

### ISSUE THREAD

**Issue by MuratUrsavas** [jesseduffield/lazygit#1000]
I'm using Git submodules for managing my libraries and they are generally nested. For committing a parent repo I generally need to enter three submodules individually and then enter same or similar commit messages. Normally I was copying the commit message and apply all other remaining repos while using other GUI's. But Lazygit does not allow me to do it. Shift + Arrow does not work. Mouse drag just moves the cursor does not select the message.

It would be nice if we could be able to copy the commit message to clipboard.

**Comment by jesseduffield** [comment]
you can shift+drag to copy it, however I agree this should be a shortcut

**Comment by MuratUrsavas** [comment]
Didn't know that, thank you.

**Comment by MuratUrsavas** [comment]
By the way, sorry for taking this pretty issue number for a cheesy report :)

**Comment by jesseduffield** [comment]
All good I completely forgot to congratulate you on getting it!

**Comment by jesseduffield** [comment]
@nullawhale has made a PR for this which I've just merged to master (don't let the closed status mislead you we just had some merge conflict issues). You can now copy a commit message with <c-y> but with the limitation that we don't yet support multiline messages (when you paste them into the commit message panel, the first newline is interpreted as an enter key and it submits the message, meaning the remaining characters are all interpreted as keybindings unfortunately).

The way around this currently is to paste the commit message into your editor when you press `shift+c` instead of pressing `c` and using the in-lazygit editor.

At any rate I'll close this issue but let me know if you have any more problems :)

**Comment by MuratUrsavas** [comment]
Thanks Jesse, I admire your efforts for an open source software, which is delightful to use.
