### ISSUE TITLE
Visualize the commits for all branches

### ISSUE THREAD

**Issue by cbenz** [jesseduffield/lazygit#1053]
I would like to be able to visualize the commit history for all branches.

That would be the equivalent of running `gitk --all` or `git log --graph --all`.

I don't really know from which panel the action should be initiated. Maybe the "status" panel with a `l` keybinding, for "log"?

There is already a `branchLogCmd` setting. A new `allBranchesLogCmd` could be added.

```yaml
    branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
```

Does it make sense?

**Comment by jesseduffield** [comment]
Makes sense. I too am not sure which panel this makes the most sense in, but the status panel would be the best fit. We currently only have tabs on side panels but we might want to introduce tabs to the main panel so that you can switch between this log graph and what currently appears when you're in the status panel. Lazydocker has this logic already and it shouldn't be too hard to recreate in lazygit. What are your thoughts?

**Comment by cbenz** [comment]
I like the idea of using tabs to the main panel. I'm wondering how the user would change focus between the status and the main panels, but I'm re-installing lazydocker to see how it's done.

Idea: when the status panel is focused pressing `Enter` would focus the main panel, then use `[` and `]` to change tabs, and `Escape` to focus the status panel again.
