### ISSUE TITLE
Can I open my mergetool fom lazygit directly?

### ISSUE THREAD

**Issue by thales-maciel** [jesseduffield/lazygit#1090]
**Is your feature request related to a problem? Please describe.**
I don't know if there is a way to open my mergetool directly fom lazygit. I usually have to type the custom command, which doesn't feels right.

**Describe the solution you'd like**
As I said, I don't really know if this isn't possible, so there are two possible solutions:
1. Add option to send the command `git mergetool`
2. Add required info to the README file.

**Comment by jesseduffield** [comment]
There is really no good reason why this isn't yet built into lazygit, but in lieu of the feature being properly added, I've added an example of how to do this with [custom commands](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#opening-git-mergetool).

One thing we will need to know is whether the typical merge tool is run within the terminal or if it's outside the terminal. If it's inside the terminal we'll need to switch over to the subprocess (hence the `subprocess: true` in the custom command example). Otherwise we'll need to just run the command without switching explicitly
