### ISSUE TITLE
Crash when scrolling

### ISSUE THREAD

**Issue by znculee** [jesseduffield/lazygit#1092]
**Describe the bug**
Crash when scrolling on remote Linux server instead of local Mac

**To Reproduce**
1. ssh to a remote Linux server
2. Go to a git repo
3. Scroll down very fast with mouse wheel or trackpad
4. lazygit will quit unexpectedly

**Expected behavior**
Not quit when scrolling

**Desktop (please complete the following information):**
commit=, build date=, build source=homebrew, version=0.23.7, os=linux, arch=amd64

**Comment by pizzafanatic** [comment]
I am encountering a similar issue as well. I suspect the ssh'ing part of this is irrelevant. For me it shows up when scrolling through the diff panel (right hand side) of a large commit.

commit=, build date=, build source=apt-get, version=0.25, os=Linux: Ubuntu 20.04, arch=

One thing I have noticed is that this doesn't happen when scrolling with my mouse's scroll wheel. It only happens when using my touchpad, when trying to scroll down quickly. It might my fingers are not fast enough to achieve the required scrolling speed at which the bug occurs. However, it is also likely is that it has something to do with the way accelerated/non-linear scrolling is implemented under Linux, in my case using 'old fashioned' synaptic drivers.

**Comment by jesseduffield** [comment]
@znculee @pizzafanatic could you guys try again on the latest release?

**Comment by znculee** [comment]
Problem solved! Thanks! @jesseduffield
