### ISSUE TITLE
verbose commit when writing commit msg using editor

### ISSUE THREAD

**Issue by c02y** [jesseduffield/lazygit#1164]
**Is your feature request related to a problem? Please describe.**
When using `C` to writing commit msg using my editor, it is better to list all the changes in the editor, like `git commit --verbose`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fitzterra** [comment]
This is also a feature I miss very much in lazygit and I started looking at how to enhance this.

The way lazygit handles commit-with-editor is to simply start a subprocess with the command `git commit`. Instead of changing lazygit for this specifically, from git 9.2.0 onwards, you can make git always use verbose mode when committing:

`git config --global commit.verbose true`

reference: https://stackoverflow.com/a/37848889/3671582

Commit with editor from lazygit is now totally usable for me :smiley:

**Comment by c02y** [comment]
@fitzterra Thanks, it works.
