### ISSUE TITLE
Keybindings for editors

### ISSUE THREAD

**Issue by d6e** [jesseduffield/lazygit#12]
I've noticed there's keybindings set for specific editors such as "s" for "sublime" and "v" for "vscode". If I may suggest, instead of making a new keybinding for every editor, maybe it might be better to make one keybinding for opening whatever editor is specified with the $EDITOR, $GIT_EDITOR, or $VISUAL environment variable. [This is what git does to determine which editor to use.](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables)

**Comment by srstevenson** [comment]
> I'm assuming the same is true of other non-OSX platforms

This isn't the case; `open(1)` is inherited from NextStep and not present on non-macOS platforms. The conventional behaviour is to check `$VISUAL` et cetera as @d6e suggests, falling back to `vi` if none of those variables are defined.

**Comment by jesseduffield** [comment]
@srstevenson thanks for the clarification. I've realised that opening vi isn't as clear cut as I thought it would be, because unlike standalone applications like sublime or vscode, it needs to be called as a subprocess in the current terminal. I've put up a PR that kind of does the job but after focus is returned to the app it gets very glitchy. Any contributions here would be greatly appreciated :)
https://github.com/jesseduffield/lazygit/pull/18

**Comment by jesseduffield** [comment]
@d6e @srstevenson This behaviour is now implemented. The app tries the git editor, then VISUAL, then EDITOR, then vi. This is for the 'e' keybinding which is to edit the file.
