### ISSUE TITLE
No longer shows tracked files first in files view since 0.27

### ISSUE THREAD

**Issue by marcjay** [jesseduffield/lazygit#1259]
**Describe the bug**
On 0.26, if you have changes to tracked files, they would appear at the top of the list of the Files list, followed by untracked files, alphabetically.
As of 0.27 (and tested up to 0.27.4), all files are listed alphabetically, with tracked files appearing in the list of untracked files, and I cannot see a configuration option to go back to the old sort ordering. Toggling the new tree mode does not help. I may be alone here but for me it was most useful to see tracked files first, and this also matches the behaviour of `git status` 

**To Reproduce**
1. Create some untracked files
2. Modify some tracked files
3. Open lazygit

**Expected behavior**
Untracked files show at the top, as in 0.26. Instead, all files are listed alphabetically, and tracked files are in amongst untracked files

**Desktop (please complete the following information):**
 - OS: Mac
 - Lazygit Version: 0.27.4

**Comment by jesseduffield** [comment]
I'm happy to make this the default i.e. show merge conflict files, then tracked files, then untracked files. Just for the flat view though, I think the tree view makes sense being purely alphabetical, but I'm open to being persuaded otherwise

**Comment by marcjay** [comment]
Yup agree (and I think the new tree view is very cool). Personally not against the new order being the default, but would love for there to be a config option to revert to the old 'git status' order if so

**Comment by ristillu** [comment]
I also would definitely prefer the behavior @marcjay prefers. In our main repo for various reasons I currently have 47 untracked files and when I make some changes to tracked files I have to page through to find them. Given by default tracked modified files have the same color as untracked files there's a high probability I will miss files I want to update.

Of course, the underlying problem is I should clean up my local repo or gitignore but I still upvote marcjay's request.

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1261 :)

**Comment by marcjay** [comment]
Thank you!!
