### ISSUE TITLE
Sort remote branches

### ISSUE THREAD

**Issue by Jayphen** [jesseduffield/lazygit#1267]
I often like to check out branches that my colleagues are working on to give feedback or assist. At the moment, it seems that the `Remotes` tab sorts all branches alphabetically, which is only useful if you know the name of the branch you're seeking.

It would be great to have some sorting options here - `created`, `last modified`, `alpha` for example.

**Comment by Holi0317** [comment]
As a user, I think I will change the sort criteria often. Sometimes I would want to checkout a release branch (where sort by name makes the most sense) while other time I may want to check other's PR (where sort by last modified makes sense).

I think the sort option should have an key-binding to it instead of being a config option.

**Comment by jesseduffield** [comment]
We've implemented sorting for local branches now so it should be pretty easy to copy what we're doing there and apply it to the remote branches view too. I'll put a 'good first issue' label on this. Let me know if either of you are up for implementing this @Jayphen @Holi0317

**Comment by stefanhaller** [comment]
Erm, sorting remote branches was implemented in #3171. 😄

**Comment by jesseduffield** [comment]
Ah yes, the easiest feature to implement is the one that's already implemented haha. Good work everyone.
