### ISSUE TITLE
Text highliting

### ISSUE THREAD

**Issue by MiroslavMikus** [jesseduffield/lazygit#1271]
**Describe the bug**
The selected text should be highlighted.

**Screenshots**
![image](https://user-images.githubusercontent.com/29312172/114583318-c3863980-9c81-11eb-8ffd-7449fddbb043.png)
Left is 0.25.1
Right is 0.27.4

**Desktop:**
OS: Windows 10.0.19042
Terminal:
- WindowsTerminal 1.6.10571.0 (tested and gif)
- Powershell terminal 5.1.19041.610 (tested)
Powershell: 7.1.3
Lazygit Version 0.27.4

**Comment by rgwood** [comment]
I'm experiencing this issue in Windows Terminal as well. In all of the left panes (Files, Local Branches, Commits, etc.) the selected list item is formatted identically to the unselected items.

This occurs in multiple [built-in colour schemes](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/color-schemes) (tested: Campbell, Tango Dark, Tango Light, One Half Dark). 

The issue was not present in Lazygit 0.26.1.

**Comment by MiroslavMikus** [comment]
The workaround for now would be the config:
```yaml
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
```

**Comment by jesseduffield** [comment]
hmm this would be related to our upgrade from termbox to tcell, though I'm not sure specifically why highlighting would fail in this case

**Comment by LegalOwl** [comment]
I have got the exact same issue. At first I thought the keymapping for navigating in the left panes have changed.
Where exactly do I have to put the config you posted @MiroslavMikus?

**Comment by MiroslavMikus** [comment]
Hey @LegalOwl,
Depends on your OS. You can find the documentation in [docs/Config.md](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) Folder in this repo.

**Comment by jesseduffield** [comment]
you can also press ‘o’ while the status panel is focused from within lazygit to open the config file

**Comment by jesseduffield** [comment]
I'm gonna close this off because in 0.35 we by default use a blue background on the selected line. Lemme know if I've missed anything
