### ISSUE TITLE
Crashes when resolving a merge conflict and changing the file in the `Files` panel

### ISSUE THREAD

**Issue by HannesOlszewski** [jesseduffield/lazygit#1297]
**Describe the bug**
Crashes when resolving a merge conflict and changing the file in the `Files` panel.

**To Reproduce**
1. Merge a branch with merge conflicts
2. Change selected file with conflicts with the `arrow-down` key
3. Lazygit crashes and prints error message

**Expected behavior**
The program not crashing.

**Desktop (please complete the following information):**
 - OS: MacOS 11.0 (with Apple Silicon cpu if that's important)
 - Lazygit Version v0.28.1

**Additional context**
The error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x104bd794c]

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui/mergeconflicts.findConflicts(0x1400069e800, 0x15ad, 0x1400021c1c0, 0x104e92318, 0x14000212fa0)
	/home/runner/work/lazygit/lazygit/pkg/gui/mergeconflicts/state.go:105 +0x10c
github.com/jesseduffield/lazygit/pkg/gui/mergeconflicts.(*State).SetConflictsFromCat(0x140002dc100, 0x1400069e800, 0x15ad)
	/home/runner/work/lazygit/lazygit/pkg/gui/mergeconflicts/state.go:88 +0x30
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshMergePanel(0x1400021c1c0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:163 +0x110
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handlePickHunk.func1(0x14000136060, 0x104e71a58)
	/home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:94 +0x9c
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).withMergeConflictLock(0x1400021c1c0, 0x14000171698, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:312 +0xa8
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).handlePickHunk(0x1400021c1c0, 0x10475fe9c, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/merge_panel.go:77 +0x44
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).wrappedHandler.func1(0x14000203380, 0x140000bcb40, 0x0, 0x1400008d880)
	/home/runner/work/lazygit/lazygit/pkg/gui/confirmation_panel.go:314 +0x28
github.com/jesseduffield/gocui.(*Gui).execKeybinding(0x14000203380, 0x140000bcb40, 0x1400051d280, 0x2, 0x1, 0x1)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1167 +0x5c
github.com/jesseduffield/gocui.(*Gui).execKeybindings(0x14000203380, 0x140000bcb40, 0x140001718c8, 0x14000586160, 0x14000000180, 0x140001718b8)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1135 +0x1a8
github.com/jesseduffield/gocui.(*Gui).onKey(0x14000203380, 0x140001718c8, 0x14000090030, 0x140000c2000)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:1060 +0x280
github.com/jesseduffield/gocui.(*Gui).handleEvent(0x14000203380, 0x140001718c8, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:651 +0x44
github.com/jesseduffield/gocui.(*Gui).MainLoop(0x14000203380, 0x14000000004, 0x1400031f9d8)
	/home/runner/work/lazygit/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:611 +0x138
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0x1400021c1c0, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:540 +0x43c
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1(0x1400021c101, 0x14000030540)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:548 +0x2c
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x1400031fb28, 0x0, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/utils/utils.go:380 +0x5c
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0x1400021c1c0, 0x31, 0x104c5ba00)
	/home/runner/work/lazygit/lazygit/pkg/gui/gui.go:547 +0x70
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0x1400029db20, 0x1400027e630, 0x0)
	/home/runner/work/lazygit/lazygit/pkg/app/app.go:242 +0x84
main.main()
	/home/runner/work/lazygit/lazygit/main.go:127 +0x9fc
```

**Comment by jmcdl** [comment]
I was about to report this exact same issue today on the same architecture.

**Comment by Krismix1** [comment]
I am encountering the same issue. I have managed to put together a folder with a file that reproduces the error (see the attached zip), and identified where it fails.
The issue appears when a merge conflict was created, but the file under conflict was also renamed.
In this case, `git` inserts the original and new file name in the lines delimiting the conflict, e.g. `<<<<<<< Updated upstream:test
`. On line [102](https://github.com/jesseduffield/lazygit/blob/98375dc902513a8b0759985a270d8d895cba1199/pkg/gui/mergeconflicts/state.go#L102) the parser is looking for the beginning of conflict. However, the line with the file name does not match any pattern (it doesn't even fit the `if` under `default`). The parses then continues and finds the `=======`. It then tries to modify the `middle` property on line [105](https://github.com/jesseduffield/lazygit/blob/98375dc902513a8b0759985a270d8d895cba1199/pkg/gui/mergeconflicts/state.go#L105), but `newConflict` is `nil`, since line 103 was never executed.

Reproduction steps:
1. In a git repo, create a file `test1` and have a line with test content. Commit this file.
2. Modify a line from the file, and stash the changes
3. Now modify the same line, but rename the file to something else
4. Stage the local changes
5. Pop the last stash
6. Try to view the file with lazygit

[merge-conflict.zip](https://github.com/jesseduffield/lazygit/files/6429735/merge-conflict.zip)

Unfortunately, I don't know go to fix this myself.
