### ISSUE TITLE
Option to ignore whitespace changes

### ISSUE THREAD

**Issue by llk23r** [jesseduffield/lazygit#1303]
**Topic**
Is it possible to ignore/toggle-hide whitespaces in diffs like in https://github.blog/2018-05-01-ignore-white-space-in-code-review? If yes, how do I do it? 

**Your thoughts**
While it's most likely a Github thing to hide the whitespaces in PR reviews only, want to know if it's doable in lazygit.

**Comment by geins** [comment]
Would be really a nice option :)

**Comment by Liberatys** [comment]
If I understand you correctly then there is already a solution for this in git.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_whitespace

**Comment by Ryooooooga** [comment]
`<c-w>` keybinding was added in  https://github.com/jesseduffield/lazygit/commit/a9f04d3925bff4ec487a8c622ce84c79ef64ab87 .

**Comment by llk23r** [comment]
@Ryooooooga, thanks! Closing the issue.

**Comment by all500234765** [comment]
Can we have same thing but for commits?

**Comment by mark2185** [comment]
Could you please clarify? You want to ignore commits that have only whitespace changes, or?

**Comment by utkarshgupta137** [comment]
In commit diffs, this setting is not respected.
Also, how to change it so that whitespace is ignored by default?

**Comment by stefanhaller** [comment]
> In commit diffs, this setting is not respected.

Which version are you using? This was added in 0.38.

> Also, how to change it so that whitespace is ignored by default?

There's no way to do that, currently.

**Comment by utkarshgupta137** [comment]
> > In commit diffs, this setting is not respected.
> 
> Which version are you using? This was added in 0.38.

Okay, it is working now, but the toggle key doesn't work in the commit area, so I didn't realize it was supported.

> > Also, how to change it so that whitespace is ignored by default?
> 
> There's no way to do that, currently.

Any plans or tracking issue for this feature? I don't think I ever want to start with whitespace diffs.

**Comment by stefanhaller** [comment]
I don't have any plans to work on this, as I don't need it. I tend to work only on things that I want myself. 😄 

I'm also not aware of any issue that tracks this, so feel free to file one.

I'll just say that I don't find it totally trivial to get the UX for this right, but it's probably better to discuss this in the issue once we have it, rather than here.

**Comment by jesseduffield** [comment]
As for whitespace being ignored by default, we should have a config value for it and that config value should be updated by lazygit when toggling whitespace within the app. That's something I'm happy to work on as it would be the first time we let lazygit write to the user's config

**Comment by stefanhaller** [comment]
Well, that's exactly what I meant when I said it's not trivial to get this right. 😄 

I did consider this as one of the possible solutions, but I don't want this behavior myself. Since I want "ignore whitespace" to be off most of the time, I don't want lazygit to remember the setting. I already have the problem now (occasionally) that the setting stays on for longer than I want without me realizing it, so at least when I restart lazygit I'm happy that it reverts to sane defaults. (Side note: I have a similar issue with diff mode (`shift-W`), sometimes I accidentally stay in that mode and then it confuses the hell out of me when I move around and none of the diffs I look at make any sense.)

**Comment by jesseduffield** [comment]
I too have that issue with diff mode sometimes, but I'd say it's different to toggling whitespace because diff mode is not something anybody would want to remain on for a long length of time, whereas I assume many people would indeed want whitespace mode turned on/off permanently. Then again, Github doesn't persist whitespace settings so that's a factor to consider.

**Comment by utkarshgupta137** [comment]
My 2c: Add a config option instead of persisting it in the state. On top of that, a visual indicator to show that whitespace is being ignored would be nice.

**Comment by jesseduffield** [comment]
I'm happy with that. Not sure where to put a visual indicator though: realestate is tight. I'm open to suggestions

**Comment by utkarshgupta137** [comment]
<img width="1636" alt="image" src="https://github.com/jesseduffield/lazygit/assets/5155100/196aad09-c47f-44d6-81b1-5d399b274465">

Instead of `Unstaged Changes`, we could have `Unstaged Changes [Whitespace Hidden]`.

**Comment by toh995** [comment]
Do we have a config option to hide whitespace by default? Or is it not added yet?

I couldn't find an option looking at the [config docs.](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md)

Should we open a separate github issue as a feature request?

**Comment by jesseduffield** [comment]
@toh995 it's not currently supported, so yes, please raise an issue.

**Comment by stefanhaller** [comment]
I just started working on a PR; adding the config is trivial, but writing it back when it is toggled is not. Lazygit supports multiple config files (with the `--use-config-file` option), so it's not obvious which of these we should write it to. We could try to work out which of them contained the option, but this seems like a lot of work; also, what if it's none?

But then I also wonder if we really need to write the changed config back at all. For those requesting the option, it seems they always want it on, so it's unlikely that they change their mind and suddenly want to have it off forever just because they toggled it once. And for me it's the opposite, as I explained [above](https://github.com/jesseduffield/lazygit/issues/1303#issuecomment-1552451686). So maybe it's just good enough to add the config as the initial value, still allow toggling it at runtime, but just not write it back. What do you think @jesseduffield?

**Comment by utkarshgupta137** [comment]
Would it be easier to store the state in `state.yml`?

**Comment by stefanhaller** [comment]
Yes, but that wouldn't play well with adding it as a user config. Or do you mean, not add the config, _only_ persist the value in state.yml? Yes, that would also work.

**Comment by utkarshgupta137** [comment]
Yes, it just being a state makes more sense IMO, similar to `hidecommandlog`.

**Comment by toh995** [comment]
@stefanhaller

> So maybe it's just good enough to add the config as the initial value, still allow toggling it at runtime, but just not write it back.

I'd be happy with this approach! This is exactly what I was thinking too 😄

**Comment by stefanhaller** [comment]
I really can't decide which approach I like better, so I made PRs for both: #2830, #2831
