### ISSUE TITLE
Cannot enter the character # into the commit message

### ISSUE THREAD

**Issue by amatosg** [jesseduffield/lazygit#1312]
**Describe the bug**
While using Windows and an Apple Magic Keyboard (I don't know if that's relevant, but still...), I'm not able to enter any special characters, including "#" (neither can I past it)

**To Reproduce**
1. Stage some changes
2. Press c and try to enter #

**Expected behavior**
The character # would appear in the commit message

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows
 - Lazygit Version: commit=9190e9beac90d80e854a726134b12e15d239df45, build date=2021-04-20T11:09:15Z, build source=binaryRelease, version=0.28.1, os=windows, arch=amd64

**Comment by amatosg** [comment]
Same happens to "[" and "]"

**Comment by ArnoNuyts** [comment]
I have a similar issue with these characters. Any character where I have to make a combination of Alt Gr + key doesn't work. If I use lazygit via SSH on a linux machine these characters work fine.

OS: Windows 10
Lazygit: 0.29

**Comment by clooudch** [comment]
I think ALT and ALTGR is not working at all. You can not:
- Use a character which requires ALT or ALTGR in a commit or another text field.
- Use a command shortcut which requires ALT or ALTGR like `[` or `]` for switching tabs.

Probably only an issue for certain keyboard layouts, because when I switch to english (US) keyboard, then I can use those characters and shortcuts as they do not require ALT or ALTGR.

I am using Windows btw.

**Comment by clooudch** [comment]
Does this maybe have something to do with `termbox.InputAlt` being used as the default?

Because when this mode is enabled then it seems like `ModAlt` is being set on the key event in case ALT or ALTGR is pressed.

From `termbox-go`'s [source](https://github.com/nsf/termbox-go/blob/64616e880de4196ee81bde96c0be1ae35b5ec521/termbox_windows.go#L698):
```golang
if input_mode&InputAlt != 0 {
  if alt_mode_esc {
    e.Mod = ModAlt
    alt_mode_esc = false
  }
  if r.control_key_state&(left_alt_pressed|right_alt_pressed) != 0 {
    e.Mod = ModAlt
  }
}
```

**Comment by birgersp** [comment]
I can add the # symbol just fine (on my keyboard that's SHIFT+3)

But I cannot add newlines to commit messages. ALT+ENTER is "toggle fullscreen" on windows cmd and PowerShell terminals

Can you guys add a newline to commit messages (on a Windows PC)?
