### ISSUE TITLE
Honour git config's defaultBranch when creating a new repo

### ISSUE THREAD

**Issue by piegamesde** [jesseduffield/lazygit#1314]
**Is your feature request related to a problem? Please describe.**
GitHub has switched to using `main` as the new, well, *main* branch for a while now. And it'd be cool if lazygit had better support for this. For example, I noticed commits turning from green to yellow after renaming the branch.

**Describe the solution you'd like**
Additionally to fixing the commit color, defaulting to `main` when creating new repositories would be a bonus.

**Comment by mjarkk** [comment]
Ya agree,

> defaulting to main when creating new repositories would be a bonus.

As this change is a bit controversial in general i think we should try to respect both parties here and read `git config init.defaultbranch`.  
I would personally prefer to default to the master if `init.defaultbranch` is not set as it's still git's default but at the same time github, gitlab and bitbucket now default to main so maybe it's worth defaulting to `main` if `init.defaultbranch` is not set.

**Comment by piegamesde** [comment]
> and read git config init.defaultbranch.
> I would personally prefer to default to the master if init.defaultbranch is not set as it's still git's default but at the same time github

Yes and yes. I didn't know about this git configuration, it would be great to use it. In that case, it would also be reasonable to stick to `master` as default as long as `git` does.

**Comment by jesseduffield** [comment]
Related issue: https://github.com/jesseduffield/lazygit/issues/1062

I agree with all the above :)

Our current ethos is to let the git CLI decide what to do whenever possible so that our code stays simple and so that the user can freely switch between using the CLI and lazygit without weird differences in behaviour. In this case that means just telling git to create a new repo and whatever branch it wants to use as the default is what gets used as the default. This has the convenient side-effect of allowing us to stay out of the controversy as much as possible.

Of course, we should be honouring whatever git config the user has when we run `git init`.

I'm going to rename this issue to be specific to creating new repos because the above linked issue has a thread relating to how we handle the main branch for existing repos.

**Comment by mjarkk** [comment]
@piegamesde created #1397 it should fix the commits pannel commit colors if you are using the "main" branch name

**Comment by mark2185** [comment]
Resolved by #2020 .
