### ISSUE TITLE
Compilation on Raspberry Pi 4 failes (see solution provided)

### ISSUE THREAD

**Issue by brunomueller93** [jesseduffield/lazygit#1337]
Could not compile lazygit on a Raspberry Pi 4. 

Solution to this issue was to run: 
```
go get -u golang.org/x/term
env GOOS=linux GOARCH=arm GOARM=6 go build
```
This then successfully ran the compilation and lazygit can be run on the Raspberry Pi 4. 

I don't know much about Go but it seems that this x/term package seems to be missing on the Pi 4 by default?

**Comment by mjarkk** [comment]
Is this still an issue?
If you need to explicitly define `GOOS=linux GOARCH=arm GOARM=6` when compiling lazygit on your PI i think there is something wrong with your go installation as you should not have to define that.

About the `go get -u golang.org/x/term`
Just ran `GOOS=linux GOARCH=arm GOARM=6 go build` on my mac without the `go get -u golang.org/x/term` and it compiled just fine but that might be also because i have a shitload of go packages on my device

**Comment by jesseduffield** [comment]
Closing due to staleness. Lemme know if we need to reopen
