### ISSUE TITLE
How to support multiple remote repos at the same time?

### ISSUE THREAD

**Issue by Tim-Cao** [jesseduffield/lazygit#1425]
**Topic**
There are two remote repos in my config file
For example,
```
[remote "origin"]
	url = https://github.com/Tim-Cao/lazygit.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[remote "upstream"]
	url = https://github.com/jesseduffield/lazygit.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

When I have the following setting, execute `p` via lazygit could update my master branch on my local repo.
```
[branch "master"]
	remote = upstream
	merge = refs/heads/master
```

I have to change the config to
```
[branch "master"]
	remote = origin
	merge = refs/heads/master
```
Execute `P` via lazygit to update my master branch on my remote repo.

Is there a way to support multiple remote repos at the same time?

**Comment by waltermaldonado** [comment]
I think this is a great discussion, I am facing this problem right now, and I think it's easy to implement.
I am used to work with two remotes (fork as origin/ main repo as upstream). I need to be able to easily push my local branch to origin and also to pull from the upstream into my local branch. This makes very easy to keep the local branch updated.

I noticed the lazygit push/pull only perform `git push` and `git pull`. FWIW it's just a matter to automate `git push/pull upstream checked-out-branch/refs`. Also, I'm not sure it is pushing tags as well...

**Comment by fenguoerbian** [comment]
Currently I'm using `:` to start a custom command and just hand type the necessary git commands.

**Comment by jesseduffield** [comment]
@Tim-Cao @waltermaldonado @fenguoerbian I believe this is resolved on the master branch, where we now explicitly push/pull to/from the current branch's upstream.

@waltermaldonado as for pushing tags, we don't push tags unless you're viewing a tag in the tags panel, in which case pressing shift+P will push that tag.

**Comment by Garmelon** [comment]
In a situation with an `origin` remote (which I have write access to) and an `upstream` remote, I like to specify `branch.<name>.remote = upstream` and either `remote.pushDefault = origin` or `branch.<name>.pushRemote = origin` so that `git pull` pulls from `upstream` but `git push` pushes to `origin`.

It seems that the update 0.32.2 you mentioned broke this workflow as it always specifies the branches' remote (even for pushing), overriding/ignoring the `pushDefault` and `pushRemote` settings. I don't understand why that change was made or how it should resolve this issue, but maybe I'm using lazygit in a way it was not intended?

**Comment by mark2185** [comment]
Is this still relevant on current `master`? 

We can even set the upstream for each branch by pressing `u` in the `Branches` pane, and #1821 is marked as `closed`.

**Comment by Tim-Cao** [comment]
You're right @mark2185, press u in Branches panel is a really nice feature. Thanks for sharing.
