### ISSUE TITLE
Git bisect support

### ISSUE THREAD

**Issue by gikari** [jesseduffield/lazygit#1542]
**Is your feature request related to a problem? Please describe.**
Sometimes when I am trying to find where a regression was introduced, I want to run `git bisect`. To correctly do that I need to execute some of the commands in CLI: `git bisect start`, `good` etc

**Describe the solution you'd like**
I want lazygit to run bisect commands with shortcuts, may be with UI similar to the existing "merge" submenu.

**Comment by jesseduffield** [comment]
@gikari I've now implemented git bisect on the master branch. You open up the git bisect menu with 'b' in the commits panel. I haven't cut a release for it yet because there's an edge case that isn't yet handled, namely when somebody starts a git bisect with a good and bad commit the live on a separate branch. In that case we don't actually show the commits because we currently use the git log based on your original commit for the sake of showing the commits in context.

**Comment by jesseduffield** [comment]
Alright as of https://github.com/jesseduffield/lazygit/pull/1729 this feature is now good to go. It's on the master branch, but I'm still not gonna cut a release for a bit in case anything I've recently added breaks things

**Comment by jesseduffield** [comment]
Here's a demo:
https://user-images.githubusercontent.com/8456633/151129340-88bc568f-1e80-4584-b685-7fa18b6d9894.mov

If anybody wants to provide feedback feel free. I'll close this issue off once the feature is in a release

**Comment by TheDevelolper** [comment]
I can't seem to find the option. I'm sure I've done this before with lazygit.

**Comment by TheDevelolper** [comment]
Okay doh! it was in the readme. The option doesn't appear in the help menu though.

**Comment by stefanhaller** [comment]
> The option doesn't appear in the help menu though.

It does: 

<img width="466" alt="Image" src="https://github.com/user-attachments/assets/c9c61ebb-c122-4e27-a6ea-f9c0fbd2b683" />

**Comment by TheDevelolper** [comment]
> > The option doesn't appear in the help menu though.
> 
> It does: 
> 
> <img width="466" alt="Image" src="https://github.com/user-attachments/assets/c9c61ebb-c122-4e27-a6ea-f9c0fbd2b683" />

That's weird... oh I see it now. Perhaps I need a holiday.
