### ISSUE TITLE
Highlight reflogs green according to the default branch

### ISSUE THREAD

**Issue by ptwales** [jesseduffield/lazygit#1675]
lazygit has a convenient feature where the "Commits - Reflog" pane highlights the hashes of commits on the "master" branch in green.  Commits pushed on other branches appear red if they are only local or yellow if they have been pushed to some remote.

However, if you've configured `init.defaultBranch` to something other than "master" (ie "main"), then all commits on your default branch will always appear yellow.  I don't see anything in the [sample config](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md) to change that behavior. I haven't yet found it in the code but I believe this feature is hard coded somewhere to only highlight green for the "master" branch.  

Ideally, lazygit would show commits hashes in green if they were on the default branch of the repository.  I don't know what git command shows that per-repository but `git config init.defaultBranch` will show the per-user default, which IMO is better than hard-coded "master".

For reference: if you set `git config init.deafultBranch main`, create a new repo and add an initial commit.  Then your first and only commit to that repo will be highlighted in yellow instead of green.

**Comment by jesseduffield** [comment]
This is a duplicate of https://github.com/jesseduffield/lazygit/issues/1314

I wish there was a git config thing to say which branch was the default for a given repo, but it appears that's still not a thing. I'm not sure how I feel about using the user's default given that the typical user will presumably be working with repos owned by somebody else, and multiple at that.

There's a PR up for dealing with the ambiguity but it's a bit stale because I haven't felt comfortable about the complexity cost https://github.com/jesseduffield/lazygit/pull/1397/files

If you have any ideas on the topic let me know :) I'll close this issue for now and further discussion can take place on the original issue linked above
