### ISSUE TITLE
Change color of files in the Submodules list.

### ISSUE THREAD

**Issue by aniketgm** [jesseduffield/lazygit#1685]
**Topic**
Is there a way to change the color of the Files in the Submodules list ? I went through the docs, however, I can't seem to find and understand how to make that change ? And the 'Red' color is really straining the eyes. What I mean by that is this:

Please check out the 2nd Tab.
![image](https://user-images.githubusercontent.com/14215698/149726987-a984a753-98ad-4a3e-88dc-e9549c3d693e.png)

**Comment by jesseduffield** [comment]
This is currently hard coded but making it configurable is super easy: just a matter of adding an 'UnstagedChangesColor' to our theme config (see `pkg/theme/theme.go`) and then using `theme.UnstagedChangesColor` instead of `style.FgRed` in `pkg/gui/presentation/files.go`. You can search the codebase for `CherryPickedCommitFgColor` to see an example of a configurable color.

If you wanna pick this up let me know! At any rate I'll add a good-first-issue label

**Comment by nullishamy** [comment]
This was never closed but the PR was.
