### ISSUE TITLE
"revert commit" should ask for confirmation

### ISSUE THREAD

**Issue by fizzybits** [jesseduffield/lazygit#1706]
The keybinding for "create tag" is "T" while "revert commit" is lowercase "t".

As "revert commit" is a potentially destructive/undesired action and also shares a key with "create tag", the "revert commit" function should ask for confirmation.

**Comment by jesseduffield** [comment]
I agree, I mix up T and t myself. I'll add a good-first-issue label because this should be straightforward. relevant function is `handleCommitRevert()` in `pkg/gui/commits_panel.go`, just need to wrap it in a `gui.ask` call (examples of doing this appear elsewhere in the file).

No need to make it configurable, I think it's fine for everybody to see the confirmation prompt

**Comment by jesseduffield** [comment]
btw @fizzybits if you want to take a stab at the PR yourself let me know and I can give you pointers!

**Comment by glendsoza** [comment]
I wanted to take a look into this and created a PR here https://github.com/jesseduffield/lazygit/pull/1711
