### ISSUE TITLE
I somehow got into an interactive rebase without trying to

### ISSUE THREAD

**Issue by sdegutis** [jesseduffield/lazygit#1708]
Earlier I accidentally pressed <kbd>R</kbd> thinking it would refresh, but since I was focused on the wrong panel, I guess it must have tried to start an interactive rebase? I pressed <kbd>Esc</kbd> thinking it would be enough to cancel whatever strange thing popped up at the time. After that I continued working and committing changes. But it must not have been enough, because just now, I looked at my commit history, and *apparently I'm in an interactive rebase and HEAD is several commits separated from the branch I was working on.* This is unexpected and unpleasant. Now I have to go through reflog or something to try to make sure everything is ok.

I'd say this is a UX bug: if I accidentally press something that could be destructive, and an unexpected panel comes up, that's already a bit scary, but as long as I can hit <kbd>Esc</kbd> then it should be fine if everything goes back to what it was before. I get that this is a power tool for power users, but I still think the UX that I ran into today when trying lazygit is very much not good even for us.

**Comment by jesseduffield** [comment]
Just tried replicating but couldn't, although I think we should at least have a confirmation panel if somebody presses 'R'

**Comment by sdegutis** [comment]
🤷 If nobody else has complained about it, don't worry about it. I'm probably just not in the target audience of lazygit I think. It has a lot of defaults and behaviors that are very much unintuitive to me. So this is probably not a bug in lazygit as much as it is just me not being suitable for it.

**Comment by jesseduffield** [comment]
@sdegutis If you don't mind, could you elaborate on some of the unintuitive stuff? If something is unintuitive to you, there's a good chance it's unintuitive to others

**Comment by sdegutis** [comment]
I'm not so sure I'm representative of any typical users. But if you'd still like, tomorrow I'll try using it again and take notes throughout the day and send them here after work (if I can remember).

**Comment by jesseduffield** [comment]
Thanks @sdegutis I appreciate it!

**Comment by sdegutis** [comment]
Partial feedback (been OOO half the day):

* I expected key "R" would be "Refresh" globally.

* I expected arrow keys in Files to work like in VS Code.

* When staging by lines/hunks, I thought Shift-Up/Down would select (they just move).

* In staging thing, I thought Left/Right would switch between unstaged/staged panels.

* When done with staging, I thought Tab/Shift-Tab would get me back to Files.

* Took me a while to realize red commits meant unpushed.

* Looked for multi-line commit option, can't find it --- assuming it's just not there.

* Several times I mixed up "Esc" and "q" and ended up quitting --- probably muscle memory from my Emacs days (my fault).

**Comment by sdegutis** [comment]
Take that feedback with a grain of salt, I've used way too many softwares over the years to be a typical user.

Also your app is impressive and useful. Even with some things unintuitive for me, it's still better than Sourcetree.

**Comment by sdegutis** [comment]
* It threw me off when I tried to scroll through a list of staged and unstaged files, and sometimes the box on the right was split (staged/unstaged) and sometimes it was the same but changed role: for one file, staged, for another, unstaged, so that I had to pay attention to the title of that panel and/or the selected item to know whether the file's changes were all staged or all unstaged. Could be because I'm used to GitX where it always shows both, but in general I find it easier to quickly look at a bunch of staged changes by just staring at the main panel while pressing up/down to switch files.

**Comment by sdegutis** [comment]
@jesseduffield Out of curiosity, how do you interface with git so reliably? I tried looking through your source briefly for files with "git" in the name and couldn't find anything obvious. I've been wanting for years to try my hand at a very simple git client, but accessing all this git info seems like black magic to me. I tried once to inspect magit's source and output to see if I could figure it out but wasn't successful. Your built-in git command log also only shows some commands, but not things like how you're getting status and diffs. Are you just accessing this stuff via git CLI directly, or using a lib?

**Comment by sdegutis** [comment]
*sigh* I once again pressed some key in the wrong panel, and even though I'm on the branch I was working on, several commits are missing. I don't see any rebase in progress, the work is just gone. I'm sure it's in reflog, but this is too difficult to work with.

**Comment by sdegutis** [comment]
Fwiw I have started taking notes on all the git clients I have used, and why none of them fit my needs. It will probably prove that I'm not an ideal user of lazygit and that my feedback needs a grain of salt. https://github.com/sdegutis/ideal-git-client/blob/main/README.md

**Comment by jesseduffield** [comment]
Thanks for the detailed feedback. I would say that based on your feedback you actually are fairly representative. I'm going to make a new issue about improving the UX https://github.com/jesseduffield/lazygit/issues/1712 and I'll add a few things that you mentioned.

> I expected key "R" would be "Refresh" globally.
* will address in new issue

> I keep trying to commit with Ctrl-Enter instead of just Enter.
* will address in new issue. Currently it's enter to submit and alt-enter to add a newline

> I just tried to select multiple files with Shift-Up/Down in Files panel to act on them with space/delete.
* My understanding was that terminals don't support shift up/down. If they do we should do that (although we don't currently support selecting a range of files)

> I just tried to discard an untracked file with Delete.
* will address in new issue, that's a quick win

> I still don't know how to get rid of only non-ignored untracked files without nuking node_modules/etc also.
* does `git clean -fd` suffice?

> I expected arrow keys in Files to work like in VS Code.
* We should do this. When I first made lazygit, shift+tab wasn't possible with the keybinding library I used, so instead used left/right for switching panels. As such we've lost the ability to use those. Will address in new issue

> When staging by lines/hunks, I thought Shift-Up/Down would select (they just move).
* same as above. with shift+up/down. We currently use 'v' to begin selecting a line range there because it was suggested by somebody who had used that keybinding in another popular terminal app (perhaps vim)

> In staging thing, I thought Left/Right would switch between unstaged/staged panels.
* this is reasonable.

> When done with staging, I thought Tab/Shift-Tab would get me back to Files.
* I feel like escape still makes sense here. I want to use tab/shift+tab for moving through things vertically (e.g. moving through hunks in the staging panel: currently done via left/right).

> Took me a while to realize red commits meant unpushed.
* I've had this feedback before. Not sure how to make this more apparent without having some kind of walkthrough thing at the beginning. We could use a different colour, given that red is typically associated with a problem, but I like the analogy to red/yellow/green traffic lights.

> Looked for multi-line commit option, can't find it --- assuming it's just not there.
* pressing alt-enter will add a new line.
