### ISSUE TITLE
Add option to stash untracked changes

### ISSUE THREAD

**Issue by ajhynes7** [jesseduffield/lazygit#1974]
Hello, thanks for building this great tool.

Sometimes I'd like to stash work which includes new files, but I couldn't find an option in lazygit to stash untracked changes.
It'd be helpful if one of the stash options was "include untracked changes".

I believe this is equivalent to the command:

```
git stash -u
```

**Comment by mark2185** [comment]
I do believe that option is currently in `master`, could you give it a spin?

It should be under the `Stash options`, triggered by the `S` (note: uppercase) in the `Files` pane by default.

**Comment by mark2185** [comment]
You're right, I must've misremembered.

Could you explain upon what is the use case of stashing _untracked_ changes? The only thing I can think of is that you have files of the same name on a different branch and then checking out that branch might cause conflicts, otherwise the _untracked_ files shouldn't clash with anything.

**Comment by mark2185** [comment]
Alright, fair enough.

Would you like to take a shot at implementing it? 

The rest of the subcommands were added in #1870 which you can use as a reference point, stashing untracked changes would require:
- adding a new mapping in `pkg/gui/controllers/files_controller.go`
- adding a callback function in `pkg/commands/git_commands/stash.go`.

If it isn't your cup of tea, feel free to let us know and someone will implement it :)

**Comment by ajhynes7** [comment]
Sure I can give it a shot!
