### ISSUE TITLE
cannot install lazygit v0.34 and v0.35 by go install

### ISSUE THREAD

**Issue by pojiro** [jesseduffield/lazygit#2044]
**Describe the bug**

cannot install lazygit v0.34 and v0.35 by go install,.
I'm not familiar with golang, this might be relates to tag name.

tag name should be v0.35.0 ?

refs) https://go.dev/doc/modules/version-numbers

**To Reproduce**

```
# cannot install
$ go clean --modcache
$ go install github.com/jesseduffield/lazygit@v0.35
go: github.com/jesseduffield/lazygit@v0.35: no matching versions for query "v0.35"

# works fine
$ go clean --modcache
$ go install github.com/jesseduffield/lazygit@v0.32.2
go: downloading github.com/jesseduffield/lazygit v0.32.2
...

# latest download v0.32.2
$ go clean --modcache
$ go install github.com/jesseduffield/lazygit@latest
go: downloading github.com/jesseduffield/lazygit v0.32.2
```

**Expected behavior**

It would be nice to install v0.35, happy new release!!

**Comment by jesseduffield** [comment]
Ah good pickup. I've just pushed tag v0.35.0 (and cancelled the CI build just because v0.35 seems to work fine for everywhere else). You should now be able to install as expected (but might need to use GOPROXY=direct while the proxy servers update)

I'll be sure to include the patch number in all future releases.

**Comment by pojiro** [comment]
Thanks for your quick reply!!

Now it works!!
```
$ go install github.com/jesseduffield/lazygit@v0.35.0
go: downloading github.com/jesseduffield/lazygit v0.35.0
...
```

**Comment by jesseduffield** [comment]
no worries :)
