### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by remyabel** [jesseduffield/lazygit#205]
I'm gauging interest on a documentation site. Now that lazygit is gaining traction and maturity, I thought we'd have a doc site. See https://readthedocs.org/ for plenty of examples of OSS projects using RTD. You can visit what I have so far here:

https://lazygit.linuxguideandhints.com/

The repo's here: https://github.com/remyabel/lazygit-docs

I've imported the existing docs and I'm using a markdown parser so contributors can continue using that instead of restructured text if they wish. What's everyone thoughts? Good idea or should I scrap it?

**Comment by glvr182** [comment]
Nice we indeed need to make some documentation. Imo it would be best to use the standard godoc for that, since it provides readers easy access to the code aswell.

**Comment by dawidd6** [comment]
I would recommend using Github Wiki for documentation. It supports markdown and lets collaborators edit it easily.

**Comment by fiendish** [comment]
"linuxguideandhints" doesn't seem like an appropriate domain for this since lazygit runs on multiple platforms.

If you go the github wiki route, I suggest making a mirror repository for the wiki so that you can accept PRs for changes ( https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html ).

**Comment by glvr182** [comment]
@jesseduffield @remyabel We should just use godoc for documentation since the documentation we already have will be on there, see https://godoc.org/github.com/jesseduffield/lazygit
