### ISSUE TITLE
Fuzzy search for branches, both local branches and remote branches

### ISSUE THREAD

**Issue by magnusrodseth** [jesseduffield/lazygit#2057]
**Is your feature request related to a problem? Please describe.**

I find myself using quite a lot of time step-by-step iterating through all living remote branches when working in a larger team.

**Describe the solution you'd like**

I would like to search for branches using fuzzy search. Personally, this is most useful for me regarding remote branches, but I imagine the implementation for local branches is trivial to support after implementing remote branch fuzzy search.

For instance, I want to checkout the remote branch `bug/100/fix-something`. I want to search **when inside the tab for remote branch** using `/` or something, and execute a fuzzy search this way. Typing `bug` would show me all branches with the string `bug` in them.

**EDIT**

After some discussion (see thread), the issue has been re-opened, because this fuzzy-search functionality is not yet implemented. For instance, if I want to find `bug/100/fix-something`, I'd like to for instance write `bugthing`. Although this may not be a realistic search, it illustrates the desired fuzzy search functionality. Like @ooloth stated, it would act like `fzf` or `Telescope` in Neovim.

**Describe alternatives you've considered**

The current alternative is nothing. Rather, I manually iterate through all remote branches until I find what I'm looking for.

**Comment by mark2185** [comment]
Was this marked as `completed` by accident or?

**Comment by ooloth** [comment]
I'd love to see this reopened!

The current non-fuzzy search through remote branches (e.g. when I'm reviewing a PR with a branch name I half remember) doesn't let me be as lazy as I could be if that list gradually narrowed as I type the parts of the branch name I'm confident about (i.e. what happens when you search your combined local/remote branch list in VS Code).

**Comment by magnusrodseth** [comment]
> Was this marked as `completed` by accident or?

@mark2185 @ooloth I closed this manually, as I quickly discovered this functionality was already implemented. At least to the degree I desired.

When I'm in the tab branches, I can simply use `/` to fuzzy search. Do you agree that the functionality is sufficiently implemented, or is something lacking?

**Comment by mark2185** [comment]
> Do you agree that the functionality is sufficiently implemented, or is something lacking?

It's sufficient for my needs, but @ooloth seems to have different use cases, but I think that calls for a different issue/feature request.

I'm only asking because the issue was opened and then closed 2 minutes after without any explanation so I presumed it might have been a misclick or something. If you're happy with the current implementation, there's no need to do anything else.

**Comment by ooloth** [comment]
I discovered that what I'm asking for is in a WIP stage in PR #1993 (the development of which was live-streamed in [this video](https://www.youtube.com/watch?v=vFQFkdzh_Js) and [this video](https://www.youtube.com/watch?v=egM9GxgTWQI)).

@magnusrodseth When I'm in the branches area and press `/`, I get what I consider _non-fuzzy_ search functionality (i.e. the search term must match exactly and the branches list does not filter down after each keystroke to show the remaining potential matches). It's a blind search for an exact string that lets me jump through the results afterwards (similar to using `/` in vim). 

That's great, but fuzzy search with filtering would be even lazier (like fuzzy finding git branches in the VS Code command palette or any list using `fzf` or `Telescope` in neovim). Since this issue specially requested fuzzy search, I think it's still valid (and connected to the "filtering" concept in the linked PR), but I'd be happy to open a separate issue as @mark2185 suggested if you were just asking for the existing basic search, @magnusrodseth.

**Comment by magnusrodseth** [comment]
@ooloth Sounds good. 

As I have already written out the desired feature, I'd be happy to re-open this issue, and then someone can work on it 😁

**Comment by jesseduffield** [comment]
Although come to think of it, the tricky parts all related to the commits panel. If there isn't a strong use case for fuzzy-searching on the commits panel we could do that as a separate thing later

**Comment by ooloth** [comment]
@jesseduffield No apology needed! These “lazy” tools are great. 

For me, searching through local and remote branches is something I do daily (while reviewing PRs), while searching through commits is something I’ve never done. 

So launching the feature without commits panel support for now would work for me.

**Comment by magnusrodseth** [comment]
@jesseduffield I can +1 on exactly what @ooloth said. Fuzzy searching in branches is a daily thing for me, but I have never had the need to fuzzy-search through commits.

**Comment by ooloth** [comment]
@jesseduffield Apologies! I just discovered `c` in the Branches pane, which does exactly what I was looking for here: it lets me fuzzy find over the combined list of local and remote branches.

Sorry I missed that! As far as I'm concerned, that satisfies the feature request described in this issue.

Ongoing thanks for `lazygit`. 🙌

**Comment by ooloth** [comment]
Hmm...I just noticed that we can't use `n` to create a new local branch when checking out a remote branch in the `c` window...which has driven me back to searching the Branches > Remotes pane, unfortunately.

Not sure which improvement is quicker and easier to add, but I guess there still isn't a single workflow that allows both fuzzy searching branches and checking them out as local branches.

I wish I knew Go so I could help by opening a PR. 🙃

**Comment by karimkhaleel** [comment]
@ooloth This could be a temporary workaround for the time being.

```yaml
customCommands:
  - key: 'C'
    context: 'localBranches'
    command: 'git switch -c $(echo {{ .Form.Branch }} | sed "s/\(.*\/\)\(.*\/\)\(.*\)/\2\3/") {{.Form.Branch }}'
    description: 'Checkout remote branch by name with fuzzy searching'
    prompts:
      - type: 'input'
        title: 'Which branch?'
        key: 'Branch'
        suggestions:
            preset: 'remoteBranches'
```

**Comment by jesseduffield** [comment]
In the latest release (v0.39.2) we now have exact filtering in the branches panel. But if you want fuzzy filtering, that's added by https://github.com/jesseduffield/lazygit/pull/2808 (so you'll need to build lazygit from the master branch)

**Comment by jesseduffield** [comment]
@magnusrodseth can you let me know if your issue is now resolved?

**Comment by magnusrodseth** [comment]
I am very happy with the current search functionality, so for me, there's no need to keep this open anymore ☺️
