### ISSUE TITLE
Show keybinding cheatsheet in app

### ISSUE THREAD

**Issue by pax** [jesseduffield/lazygit#222]
Access within app a 'keybinding cheatsheet' in a pop-up list of [avaliable keybindings](https://github.com/jesseduffield/lazygit/blob/master/docs/Keybindings.md).

What typing <kbd>?</kbd> does on Github, Twitter, Gmail, gDrive etc.

**Comment by jesseduffield** [comment]
Sounds like a good idea to me :)

I'm not sure when I'd be able to get around to this, so if anybody is able to jump on and put up a PR let me know :)

**Comment by pax** [comment]
I just came back to close the request as I just notice the blue footer which list contextual available options. :) I'd dare suggest a bit more contrast, than the current dark blue on dark background.

**Comment by jesseduffield** [comment]
It looks good on my screen, but because I know different color themes will give different levels of contrast, I made the color of the options text configurable :) 

See here https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

This will let you change the color to whatever you like
```
gui:
  theme:
    optionsTextColor:
      - blue
```

You can open the config via the 'o' keybinding when you've focused the status panel (top panel)

**Comment by dawidd6** [comment]
I'll try making this cheatsheet.

**Comment by jesseduffield** [comment]
closin'
