### ISSUE TITLE
not able to set the vertical screen mode as default 

### ISSUE THREAD

**Issue by Nivethan-Ar** [jesseduffield/lazygit#2319]
**Describe the bug**
i want to set the **half screen mode**( achieved by pressing + ) as the default for lazy git. but setting it from the config doesnt seems to be working.

but this mainPanelSplitMode not doing any changes, i tried changing border colors and it changes instantly but not this! 
how do i make the half screen mode by default?
**To Reproduce**
1. set the mainPanelSplitMode on the config file 
```
gui:
  mainPanelSplitMode: 'vertical'  # one of 'horizontal' | 'flexible' | 'vertical'
```

**Expected behavior**
by default lazygit opens up with the vertical screen mode.

**Screenshots**
1. **currrent behaviour when i open lazygit**
![current behaviour](https://user-images.githubusercontent.com/63112138/208357921-312d37b7-a085-4cea-8a9d-5789b37c4098.png)

2. **expected behaviour when i open lazygit**
![expected behavior](https://user-images.githubusercontent.com/63112138/208357854-945db231-cf5c-4fee-b05d-193473327ad1.png)

**Version info:**
```
version=0.36.0, 
os=linux, 
arch=amd64, 
git version=2.34.1
```

**Comment by jesseduffield** [comment]
What you need is the ability to set the initial screenmode via your config (which is something not yet supported). `mainPanelSplitMode` is about whether we split the main panel horizontally or vertically, so that's a separate thing.

To implement this we need a `gui.screenMode` key in our config (see [here](https://github.com/jesseduffield/lazygit/blob/show-commit-against-branch/pkg/config/user_config.go#L31)) and we need to read it in the initialScreenMode function (see [here](https://github.com/jesseduffield/lazygit/blob/show-commit-against-branch/pkg/gui/gui.go#L304-L305)).

Then we'll need to add an example of that in the docs [here](https://github.com/jesseduffield/lazygit/blob/show-commit-against-branch/docs/Config.md#L22).

The config value will take one of three values: 'normal', 'half', and 'full', and will default to 'normal'.

This is a straightforward feature to add, so I'm gonna chuck a good-first-label issue on it.

Do you feel up to raise a PR @Nivethan-Ar ?

**Comment by Nivethan-Ar** [comment]
@jesseduffield sorry, i tried by forking the repo but i couldn't able to understand golang code since i mainly work with javascript. still i made some changes as your guidance but i'm getting some errors!

**Comment by Nivethan-Ar** [comment]
by the way setting mainPanelSplitMode to 'vertical` still show the changes in horizontal

my config file
![image](https://user-images.githubusercontent.com/63112138/208820865-073ec3dc-f1d0-4eb2-aa77-b9d35b7253d5.png)

output:
![image](https://user-images.githubusercontent.com/63112138/208820600-c04b3dba-cc6a-46bf-963f-19de34dc7115.png)
