### ISSUE TITLE
Revamping the commit message window

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#2324]
**Is your feature request related to a problem? Please describe.**
Currently we cannot insert newlines consistently, nor can we go to previous messages.

**Describe the solution you'd like**
I wanna be able to insert newlines and go to previous messages.

**Describe alternatives you've considered**
vim

**Additional context**

We could revamp it so that the popup has two parts, like the custom command popup.
The first one would just for the summary of the commit, with options such as:
- pressing `Up` or `Down` goes to the previous or next commit message, respectively
- pressing `Enter` would confirm the commit (just like it does now)
- pressing `Tab` would go to the part below

The lower one would be for the description of the commit with the following features:
- pressing `Enter` would insert a newline
- pressing `Up` or `Down` would move the cursor `Up` or `Down`
- pressing `Tab` would switch back to the upper textbox

The discussion is [here](https://github.com/jesseduffield/lazygit/issues/1790).

**Comment by seand52** [comment]
Hi @mark2185, I'd be interested in attempting to implement this. Is it still available to take?

Since it would be my first contribution, I was wondering if we could narrow down the scope a bit. I see this as two different "features" anyways. The first PR would be to add what's missing to the summary of the commit, which is:
- pressing `Up` or `Down` goes to the previous or next commit message, respectively

In a separate PR I could do the stuff related to the description of the commit.

If that's possible, I have a question about the feature of cycling through commits in the summary textbox. Does this cycle through all the commits that are listed in the git log? Or do we want to ignore merge commits for example?

**Comment by mark2185** [comment]
>  Is it still available to take?

Yup!

> I was wondering if we could narrow down the scope a bit

Well, uh, I guess, but I don't think it's really necessary. This isn't time sensitive, so feel free to take your time.

> Does this cycle through all the commits that are listed in the git log? Or do we want to ignore merge commits for example?

We can keep it simple and just cycle through all of them.

**Comment by seand52** [comment]
@mark2185 I would like to get your input regarding the description window. 

I see we have these editors in the project that we are using for the commit panel https://github.com/jesseduffield/lazygit/blob/master/pkg/gui/editors.go#L68. Unless I'm missing something, it feels like for the description panel we don't need to use these editors that override default gocui behaviour. I've tried adding the gocui `simpleEditor` and it seems to work fine for this usecase. I think we can keep the description panel simple without any fancy behaviour. For example, there's no point in adding the word count for the commit description because afaik there's no hard limit to this. So am I missing something obvious here? Or can we go ahead and use the `simplelEditor`?

**Comment by mark2185** [comment]
The only feature that the editor needs to have is interpreting `Tab` not as tab, but as `go to other editor`.

If that's doable with the `simpleEditor`, I see no reason why not to use it.

**Comment by seand52** [comment]
Sorry to bother you again :laughing: I think I have most of it done. I'm just trying to figure out one issue and I was hoping maybe you would have some insight. 

When pressing `up` and `down` to cycle through commits it would be nice to re-render the commit message length counter which is at the right of the panel. The issue I find is that when I press `up` and `down` it doesn't enter this function https://github.com/jesseduffield/lazygit/blob/master/pkg/gui/editors.go#L68 and therefore never re-renders the message length. I can't figure out if it's possible to call this function when pressing up and down, and if not do you have any idea how we could re-render the length in the commit panel?

**Comment by mark2185** [comment]
> The issue I find is that when I press up and down it doesn't enter this function 

Where does it go then? Are they ignored?

I think it'd be easier if you created a draft PR so we have something concrete we can dissect. 

> Sorry to bother you again

Don't fret, feel free to ask things anytime :)

**Comment by seand52** [comment]
I've just created the draft PR, link is here in the issue. It's still WIP, but hopefully seeing the code you can give some general tips especially for the issue with the commit window not refreshing the length when hitting `up`/`down`. Thanks!
