### ISSUE TITLE
lazygit cannot open one particular repo

### ISSUE THREAD

**Issue by zac1st1k** [jesseduffield/lazygit#239]
**Describe the bug**
Lazygit cannot open one of my repo.

**Expected behavior**
This repo is working fine all the time with other git clients

**Screenshots**

```
panic: 15:8: unquoted '\' must be followed by new line

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).setupWorktree(0xc4201b5de0)
	/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:165 +0x16b
github.com/jesseduffield/lazygit/pkg/commands.(*GitCommand).SetupGit(0xc4201b5de0)
	/go/src/github.com/jesseduffield/lazygit/pkg/commands/git.go:38 +0x47
main.main()
	/go/src/github.com/jesseduffield/lazygit/main.go:47 +0x114
```

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Lazygit Version 
commit=93ab892bdd1226f9a519a938c8b28590e71e54f3, build date=2018-08-24T23:15:14Z, version=0.1.80, os=darwin, arch=amd64

**Additional context**
lazygit was installed via brew

**Comment by jesseduffield** [comment]
If you install to the latest version, the error message is a little more useful :)

You have an unescaped backslash in your gitconfig for that repo, probably due to tower configuration. Removing that should solve the issue. Under the hood, lazygit uses the gogit package for some things, and that package fails to parse the git config when there's backslashes in it
