### ISSUE TITLE
Support for non-printable symbols in diff view

### ISSUE THREAD

**Issue by non-descriptive** [jesseduffield/lazygit#247]
It's really hard to determine what changes was made in some lines when some do trailing spaces clean-up or unifying tab policies when tabs converted to spaces or vice versa. So it would be nice to see actual difference for such changes and probably allow user to change visibility.

**Comment by scbizu** [comment]
lazygit now just  run the `git diff` command to show what has been changed.To add this kind of feature, lazygit should do something special(magical) with `git diff`.

something special: https://xaizek.github.io/2014-06-22/make-tabs-visible-in-git-diff/

**Comment by non-descriptive** [comment]
Trick not working on my macOS (other macOS users confirmation needed) and there's no `sed` on Windows

**Comment by scbizu** [comment]
use this `git diff --color | sed $'s/\t/.       /g' | less -R` at macOS , I also try to add the 
```
[core]
	pager = sed 's/\t/.       /g' | less -R
```
in my git config file , but lazygit can not parse it(because go-git can not recognize the `\`  character),so, we can not impl it by populating the git config file. 

In a word, we should use the pure git command again, we can consider this as an advanced configure.

Add the `feature required` label on this? @jesseduffield

**Comment by jesseduffield** [comment]
@scbizu we now support ignoring whitespace changes via the `<c-w>` keybinding. I'll close this issue but please let me know if it should be re-opened
