### ISSUE TITLE
Create a Gitlab MR seems to be broken

### ISSUE THREAD

**Issue by ekans** [jesseduffield/lazygit#2637]
**Describe the bug**
It seems that the Gitlab MR link to create a merge request is wrong.
(It was working before)

The MR link opened in the browser is
`.../project_name/merge_request/...`

The MR link should be
`.../project_name/-/merge_request/...`

**To Reproduce**

1. Go to 'Local branches' panel
2. Press o on a branch
3. a 404 is displayed in the browser

**Expected behavior**
Open in the browser the new merge request page in Gitlab after pressing o in Local Branches panel.

**Version info:**
_Run `lazygit --version` and paste the result here_
```
commit=, build date=, build source=homebrew, version=0.38.2, os=darwin, arch=arm64, git version=2.40.1
```
_Run `git --version` and paste the result here_
```
git version 2.40.1
```

**Comment by mark2185** [comment]
If that's the only necessary change, I'm guessing only [these two lines](https://github.com/jesseduffield/lazygit/blob/3dd96a8010a0b98c96a8ff690f0c5b63e9a682d5/pkg/commands/hosting_service/definitions.go#L36-L37) should be updated.

**Comment by ekans** [comment]
Hum, these lines have not been updated recently and I don't think something changed on Gitlab side.

Do you have an idea why it's not working now?
(I don't know exactly in which version of Lazygit but it was working recently)

**Comment by ekans** [comment]
It comes from https://gitlab.com/gitlab-org/gitlab/-/issues/28848!
Starting from 16.0.0, urls without a dash will not work.

So the url depends on the Gitlab version 😞

**Comment by mazharz** [comment]
I've done my best to follow the guidelines. I ran locally and tested with our own organization's Gitlab instance and it was working well. I'm not sure if this could be merged due to backward compatibility issues though. Let me know if you think a more complex solution must be implemented. I use this feature constantly and would like it to be fixed, I'll be willing to put time and effort as needed.

**Comment by mazharz** [comment]
I've done my best to follow the guidelines. I ran locally and tested with our own organization's Gitlab instance and it was working well. I'm not sure if this could be merged due to backward compatibility issues though. Let me know if you think a more complex solution must be implemented. I use this feature constantly and would like it to be fixed, I'll be willing to put time and effort as needed.

**Comment by donus3** [comment]
@mazharz Just adding `/-/` delimiter in URLs should be fixed.

**Comment by ekans** [comment]
@mazharz did you test your fix with a Gitlab version <16?

The new url for MRs has been introduced in Gitlab 12.8.
So it should work for most users.

**Comment by mazharz** [comment]
@ekans I hadn't, but your message gave me the idea and I ended up testing via [this](https://hub.docker.com/layers/gitlab/gitlab-ce/12.8.1-ce.0/images/sha256-01325161649a28155d8857e4f47462d2bf9406d612c11b8929d2482bfba3ad32?context=explore) container locally. All is well, both merge request URL and the view commit one are fine.

**Comment by ekans** [comment]
Great, I'm looking forward to the fix!
