### ISSUE TITLE
Support Co-Author metadata

### ISSUE THREAD

**Issue by kalebo** [jesseduffield/lazygit#2713]
This is hardly mission critical (lazygit is already fantastic at slicing and dicing git history), but it would be a nice convenience feature for adding the GitLab and GitHub `Co-authored-by` metadata. 

The main thought here is to make it easy to insert these metadata. Perhaps by adding a shortcut to the commit message dialog that spawns a little author search dialog that upon enter will insert the  `Co-authored-by: author-name <name@example.com>` metadata in the commit message body.

Another nicety here migh be that lazygit parses the commit message body for the `Co-authored-by: author-name <name@example.com>` and perhaps indicates commits with these metadata with a `*` or something in the commit view. 

You can always add these meta data easily enough, but remembering the metadata tag is annoying, and it would be much more convient to be able to quicly query other authors in the git history to populate the co-author. It's easy enough to write a  separate script that will fixup the commit with the right co-authors, but it might be nice to have it natively in lazygit. We could also use a custom command in lazygit, but that requires that the author data (name and email) to be typed by hand which would introduce typos.

**Comment by jesseduffield** [comment]
What are your thoughts on having a way to set the co-authored by value after the fact? We currently show you some author-related actions when you hit 'a' on a commit, we could add an entry for the co-author. Those options _already_ make use of suggestions to avoid typos so that could be re-used there.

FWIW you actually can include suggestions now in custom commands see [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md#input). But I'm happy for this feature to live inside lazygit

**Comment by kalebo** [comment]
Yeah, fixing up the message with co-author after the commit would be just as good for my use cases. That said I didn't realize the custom commands had suggestions! And looks like you committed the changeset  for auto-completing authors in a694c458dd so I think that pretty much wraps up this issue then! Thanks!

**Comment by omaussa** [comment]
Hey! just added this PR with the functionality of adding a new co-author to a commit, as @jesseduffield said after the commit is done we can edit the message to add the `Co-authored-by` metadata to it #2912

**Comment by kalebo** [comment]
Thanks so much!
