### ISSUE TITLE
Cherry-Picking with -x

### ISSUE THREAD

**Issue by fibbo** [jesseduffield/lazygit#2734]
**Is your feature request related to a problem? Please describe.**
I usually want to refer to the origin commit when cherry-picking. This is supported in git with the `-x` flag. I haven't found a way to enable this flag when cherry-picking in lazygit.

**Describe the solution you'd like**
One way would be upon pasting (`v`) getting a last dialog that allows the user to cherry-pick with the `x` flag or without.

**Describe alternatives you've considered**
Doing it manually on the command line or via sublime merge.

**Additional context**

**Comment by stefanhaller** [comment]
It's not as easy as that, because lazygit doesn't actually use the `git cherry-pick` command to implement copy and paste. Instead, it performs an interactive rebase with the cherrypicked commits added to the rebase-todo file as `pick` entries. It would be a lot of extra work to find a way to reword the commit messages.

**Comment by fibbo** [comment]
Thanks for the answers. I will try the custom command and see how this works.

**Comment by fibbo** [comment]
> Did it help?

Sorry, it took so long to reply - I lost it out of sight. But yes, it does work! It's actually quite neat as well. Thanks for the help.
