### ISSUE TITLE
Not too sure on right alignment of recent project names

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#2746]
Just built from `master` and noticed this change. Feels like a hit to usability if it's an intentional one:

left: new, right: old

![2023-06-26 23 47 35@2x](https://github.com/jesseduffield/lazygit/assets/191335/f5ca2c52-c5c6-4aa1-89cc-8512cf3f979c)

I'm not sure if I'm alone but it's very hard to quickly parse the list with the new alignment.

**Comment by jesseduffield** [comment]
This is the result of the default alignment logic for the menu view which is to right-align the first column ([commit](https://github.com/jesseduffield/lazygit/commit/ec3a28df4313e20aa3d73a9951c5679950e4cf04)). This was done because the first column of a menu is typically a keybinding which I think looks good with right alignment, but I agree that when it comes to recent repos, this doesn't look as good. To fix this we'll need to make the column alignment dynamic.

**Comment by peppy** [comment]
Another similar weird case:

![iTerm2 2023-07-14 at 08 04 02](https://github.com/jesseduffield/lazygit/assets/191335/70c81897-3a0c-448f-ada5-d8c818a7959e)

**Comment by peppy** [comment]
Thank you for the fix!!
