### ISSUE TITLE
Searching by commit hash does not bring results

### ISSUE THREAD

**Issue by megasuperlexa** [jesseduffield/lazygit#2862]
**Topic**
Searching by commit hash does not bring results

**Your thoughts**
I want lazygit to somehow do the same as `git show` command. 
I thought I should go to commits window and press `/` there, then commit hash. But this doesnt seem to work. 
`git show a2c23fe1beec88637e81d05cc5814c2d0d72d232` works fine.
Am I missing something?

**Comment by stefanhaller** [comment]
Searching by sha in the commits view does work if you keep two things in mind:
1. it only searches what's displayed in the view, which means that searching for the whole sha won't find it. Searching for just the first 8 characters does.
2. by default it only loads the first 300 commits, so if your sha isn't among those, it won't find it either. You can press `>` to jump to the end and force it to load the remaining commits; then it will find every sha.

**Comment by jesseduffield** [comment]
For the record, if we had filtering support in the commits view, you _could_ paste in the whole hash, because filtering is not looking at the view itself but looking at the underlying model.

This is an annoying mismatch in behaviour. I would like to either update the search functionality so that it stops looking at the view itself, or just use filtering everywhere. To be honest, I'm leaning towards the latter for the sake of consistent UX. We already filter down the commits view when you're filtering path by path via `lazygit -f <path>` so there's a precedent for it. I know that searching is better for seeing a commit in context but you can always hit escape to see the surrounding commits again.

On a separate note, it seems like various git UIs offer a specific action to jump to a commit hash, so perhaps we should provide that as its own thing. I'd prefer to just use the filtering logic but there are some benefits to having a separate action, for example not trying to filter the list as the hash is typed in / pasted.

**Comment by stefanhaller** [comment]
I was planning to look into searching using the model instead of the view as a prerequisite to https://github.com/jesseduffield/lazygit/pull/2533. Just didn't get around to it yet.

I'm still pretty convinced that jumping from hit to hit is the better UI in the commits window so that you can see the context for each hit, and especially also see the graph, which we would probably need to disable when filtering (we do when filtering by path). If you really want to change that, I'd lobby for a config option.

**Comment by stefanhaller** [comment]
As of #3642, searching for a full commit hash now works.

**Comment by jaseemabid** [comment]
@stefanhaller I just noticed an issue with searching for commits that might be related. 

For a very large repo (with well over 300 commits), searching for the full hash does bring up the commit, this works well even for old commits. 

But if I search for the commit with a unique prefix, it shows up nothing at all. Is that expected? I'll see if I can fix this myself.

**Comment by stefanhaller** [comment]
@jaseemabid I don't understand what scenario you are talking about, can you explain again? What does "unique prefix" mean?

**Comment by jaseemabid** [comment]
@stefanhaller I tried to reproduce the issue in a large public repo but I can't. So maybe this is alright.

1. Pick a very large repo, like https://github.com/python/cpython
2. Find an old commit, like `df79a1ee192` or `df79a1ee192231a75a381798bb35cefaf6c31a2a`.
3. Open lazygit, move to commits panel. 
4. Commits show '1 of 300' in the bottom right. 
5. Quickly press / > `df79a1ee192` > Enter. 
6. Search fails, shows no results. But in the background more commits gets loaded and the UI updates to `x of 129933`
7. After the commits load in the background, the UI reports a search hit but doesn't navigate to it. The panel still stays on the newest commit of the repo. 🐛 This seems like a bug. 
8. Search again for `df79a1ee192` and it works fine. 

**But** this is not what I experienced in a private repo.

1. Find an old commit. 
2. Searching for the short hash never finds the result
3. But searching for the long hash does.

**Comment by stefanhaller** [comment]
> 7. After the commits load in the background, the UI reports a search hit but doesn't navigate to it. The panel still stays on the newest commit of the repo. 🐛 This seems like a bug.

I don't think that's a bug. The commits are loaded in the background, and it would be jarring if your selection suddenly jumps to the found commit at an arbitrary time, while you might be doing something else already. You can press `n` to jump to the next (first, in this case) search result.

> 1. Find an old commit.
> 2. Searching for the short hash never finds the result
> 3. But searching for the long hash does.

I wouldn't be able to explain this, and can only assume that you made a mistake while copy/pasting the hashes. If you manage to narrow this down more, let me know.
