### ISSUE TITLE
Commits panel: commit loses focus after "edit commit" when `rebase.updateRefs` is enabled

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#2869]
**Describe the bug**

**To Reproduce**

1. Focus a commit and run "edit commit"

**Expected behavior**
Once the rebase begins, the selected commit should still have focus.

**Screenshots**

Actual behavior: once the rebase begins, the selected commit loses focus. I believe this happens because `update-refs` is inserted as a list item above.

https://github.com/jesseduffield/lazygit/assets/921609/3a6cbc9b-2d9b-4d61-b79a-9b5eefd61739

**Version info:**
commit=, build date=, build source=nix, version=0.39.4, os=darwin, arch=arm64, git version=2.40.1
git version 2.40.1

**Comment by stefanhaller** [comment]
Yes, this is caused by adding the `update-ref` command. It bothers me too, but I'm not sure how to solve it, since the refresh that we are doing after pressing `e` is asynchronous, so we can't simply add code to find the commit with the same sha and select it again afterwards. Any suggestions @jesseduffield?

**Comment by stefanhaller** [comment]
I found a way to implement this, [here's a PR](https://github.com/jesseduffield/lazygit/pull/2954).

However, this solves only half the problem. After continuing or aborting the rebase, we still have the wrong line selected. And this is much harder to solve for several reasons: if a commit below the rebase todos was selected, we can reselect it again afterwards by sha, so this is easy, but if a rebase todo was selected (more likely I'd say) we can't, because the sha will be different, or the commit might not even exist after the rebase (if it's a drop, fixup, or squash).

One option to solve this is to try to find the commit again by its commit message subject. That could work well in many cases, but fails for people who tend to name all their commits "WIP" during development.

Another option might be to try to anticipate how the selected index will change after the rebase, by counting the number of "update-ref", "drop" or "fixup" commits and moving up by that count. This will only work for continue though, not for abort, and it will also do the wrong thing when the rebase stops again with conflicts. Also, it won't work well when merge todos are involved, but that's maybe not so important since few people will ever rebase over merges.

So, it's a bit of a mess, and I'm open to suggestions what's the best way to solve this. It would be really nice to improve this, too.
