### ISSUE TITLE
Unsetting upstream when upstream is gone

### ISSUE THREAD

**Issue by mark2185** [jesseduffield/lazygit#3069]
**Describe the bug**
When the upstream for a branch is gone it says `(upstream gone)` and the option `Unset upstream of selected branch` is crossed, which is expected, _but_ if I rename the branch, the popup says `"This branch is tracking a remote. This action will only rename the local branch name etc."`, and I have no way of changing which upstream it will push to since it still tracks the old one which I cannot discard.

**To Reproduce**

1. create a new branch `test-branch`
2. push it to the upstream
3. delete the upstream
4. rename the branch to `test-branch-new-name`
5. push it
6. the upstream is `test-branch` instead of `test-branch-new-name`

**Expected behavior**
The branch pushes to the upstream with the branch names matching.

**Screenshots**

**Version info:**
Latest `master` as of yesterday.

**Additional context**
I think we should let the users _unset_ the upstream of branches whose upstream is gone, I seem to recall that that was working at one point.

**Comment by stefanhaller** [comment]
Yes, I recently ran into this myself and had to fix it on the command line.

I'm not sure I agree with your "Expected behavior" though: I don't think it should silently push to a branch with a matching name without asking. Not if `git config push.default` is set to upstream, at least.

But yes, unsetting the upstream should be allowed in this case, and it shouldn't be too hard to fix. I think this broke with #2992.

**Comment by mark2185** [comment]
> I don't think it should silently push to a branch with a matching name without asking. Not if git config push.default is set to upstream, at least.

Of course, I may have skipped a few steps, but my point was I don't want it being pushed onto the _old_ upstream name (which is also _gone_).

**Comment by stefanhaller** [comment]
> my point was I don't want it being pushed onto the _old_ upstream name (which is also _gone_).

But how is lazygit (or git for that matter) supposed to know that this is not what you want? Maybe you deleted the upstream by accident, and want to recreate it by pushing to it again.

After all, that's also what a plain `git push` on the command line would do.

I think it's up to the user to fix the situation by unsetting the upstream so that a new one can be set when pushing next. So the only thing for us to fix is to make unsetting the upstream possible in this case.

**Comment by mark2185** [comment]
> But how is lazygit (or git for that matter) supposed to know that this is not what you want?

I completely agree, it can't read minds, all I'm saying is _what I don't want to happen_, but _can't avoid_ due to the disabled option to unset the upstream. 

I'll take a stab at it soon-ish, I presume.
