### ISSUE TITLE
Diff branch against master

### ISSUE THREAD

**Issue by lpil** [jesseduffield/lazygit#311]
**Is your feature request related to a problem? Please describe.**

I often wish to view all the changes on my branch, rather than just individual commits. I typically use github or the git cli for this, but it would be nice to be able to do it in github

**Describe the solution you'd like**

I would like a keybinding that shows a diff against the master branch for a currently selected branch in the branches pane.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by jesseduffield** [comment]
Sounds reasonable, Is this something that you would always use instead of viewing the log graph for the branch? If so a solution would be to make the command for that configurable i.e. something like `git log --graph {{branchName}}` could be swapped for `git diff {{branchName}}..master`.

Alternatively a potential solution would be to allow cycling through different diff views. So you'd press a button and you'd cycle through the log graph, the diff against master, and any other things we come up with. I'm leaning towards this solution because it feels more extensible. What are your thoughts?

**Comment by lpil** [comment]
That does sound good. I would like it if I could make the diff against master the default for me rather then the commit log.
