### ISSUE TITLE
Opening URLs in browser doesn't support git instead of.

### ISSUE THREAD

**Issue by LiamKearn** [jesseduffield/lazygit#3131]
I'm not 100% sure if this is a bug on lazygit's side or something which is out of scope here.

If you're using git config's URL rewriting ([documented here](https://git-scm.com/docs/git-config/2.15.4#Documentation/git-config.txt-urlltbasegtinsteadOf)) it will save the alias in `.git/config` instead of the rewritten URL and each time you use the git client it will reinterpret it.

Lazygit's open URL in browser (git service) doesn't rewrite URLs.
<img width="1512" alt="Screenshot 2023-11-25 at 10 16 17 pm" src="https://github.com/jesseduffield/lazygit/assets/76269376/dbbd1184-d638-420a-8f1c-8143c21a5ef7">

For example my git config [is setup](https://github.com/LiamKearn/config/blob/f22ff853d6f27e42f8914509287f2d05b1887d42/.config/git/config#L25-L31) to rewrite `git clone my:lang` to be eq to `git clone git@github.com:liamkearn/lang` and `git clone gh:jesseduffield/lazygit` to `git clone git@github.com:jesseduffield/lazygit`.

**Comment by stefanhaller** [comment]
Yes, I do think this is lazygit's fault. As far as I can see, it should be easy to fix by replacing [this line](https://github.com/jesseduffield/lazygit/blob/d8059d7f7de21bedd2d989f6961f62ec48781463/pkg/gui/controllers/helpers/host_helper.go#L38) with a call to `git ls-remote --get-url origin`. Seems like a relatively simple fix if I'm not missing anything; are you up for giving it a try?

(Concretely: add a function `func (self *RemoteCommands) GetRemoteUrl(remoteName string) (string, error)` to `pkg/commands/git_commands/remote.go`, use that function in `getHostingServiceMgr`, and then maybe get rid of `ConfigCommands.GetRemoteURL` since this was the only call site.)

**Comment by LiamKearn** [comment]
Just installed a toolchain, tested this, it works fine with resolving the URL up until it's passed to the `HostingServiceMgr` where it errors.

Running `git ls-remote --get-url origin` returns: `git@github.com:jesseduffield/lazygit` for me which I'm going to guess is a valid git URL since it's resolved by git ls-remote without my custom config changes as shown below:
- first command is proof that this is a unconfigured instance of git (my config would usually resolve this gh:etc/etc format)
- second shows that `git@github.com:jesseduffield/lazygit` is valid
<img width="1512" alt="Screenshot 2023-11-29 at 12 50 10 am" src="https://github.com/jesseduffield/lazygit/assets/76269376/3ac8d9f2-3892-46d1-90e2-27d1222900bb">


It seems to me like `HostingServiceMgr` wants a `.git` suffix which fixes the issue (at least for this scheme).

I left my local builds changes [here](https://github.com/jesseduffield/lazygit/compare/master...LiamKearn:lazygit:fix-resolve-rewritten-open-urls), it's not in a state to be pulled in yet:
1. I've not used golang before so I found it a bit hard to find a path to propagate the error from the git command
2. Just doing string manipulation on the URL is not going to work since I'd guess it may have .git already or entirely different schemes don't use .git at all. **We should maybe look at addressing why `HostingServiceMgr` doesn't respect `git@github.com:jesseduffield/lazygit` without the `.git` suffix instead of tackling here. What do you think**?

I'll have a proper look later this week since I'm using this a lot at the moment.

**Comment by stefanhaller** [comment]
Took me a while to get back to this, sorry for the delay.

The `.git` suffix issue is a red herring, `HostingServiceMgr` works just fine without it. The problem was that the output of the `git ls-remote` call had a trailing line feed, and that's what `HostingServiceMgr` couldn't deal with. Stripping it makes it work. Here's a PR: #3177

**Comment by LiamKearn** [comment]
Thank you @stefanhaller!
