### ISSUE TITLE
How about supporting a local proxy for lazygit?

### ISSUE THREAD

**Issue by moqsien** [jesseduffield/lazygit#3185]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Set a local proxy for lazygit, and toggle it to be enabled or disabled.

**Describe alternatives you've considered**

**Additional context**
Support both **http** and **socks5**.

**Comment by stefanhaller** [comment]
I'm not familiar with proxies, but from what I've read, they are configured either through git config (for http) or `~/.ssh/config` (for socks). See https://cms-sw.github.io/tutorial-proxy.html for examples.

In general, if something is configurable through git itself, we avoid adding a config in lazygit, for two reasons: to keep lazygit's config space tidy, and so that lazygit behaves as close as possible to git on the command line.

Does that make sense? Do you still think there's a reason to add a config to lazygit itself?

**Comment by moqsien** [comment]
> I'm not familiar with proxies, but from what I've read, they are configured either through git config (for http) or `~/.ssh/config` (for socks). See https://cms-sw.github.io/tutorial-proxy.html for examples.
> 
> In general, if something is configurable through git itself, we avoid adding a config in lazygit, for two reasons: to keep lazygit's config space tidy, and so that lazygit behaves as close as possible to git on the command line.
> 
> Does that make sense? Do you still think there's a reason to add a config to lazygit itself?

OK. Get it.
Thanks very mush.
