### ISSUE TITLE
Should esc collapse a non-sticky range selection?

### ISSUE THREAD

**Issue by stefanhaller** [jesseduffield/lazygit#3250]
I phrased this as a question, but my clear answer is "no". I understand that esc might be useful to cancel a _sticky_ selection (because, well, it's sticky, so there should be an easy way to get rid of it). However, non-sticky selections are not annoying or in the way, they automatically collapse when you press an arrow key, so there's no need to have an explicit action to collapse them.

I have sometimes seen situations where I now need an extra esc press to cancel what I want, because the first one collapses the selection range, and I find this annoying. One example is: you start an interactive rebase, select a commit range to move it down, realize that you'd rather not do that after all, and want to abort the rebase. This now takes two esc presses.

Now, removing the esc functionality only for non-sticky selections makes it inconsistent, which might be seen as a problem. I don't think it's a huge deal, because I'd expect most people to either use sticky or non-sticky selections exclusively all the time, in which case the inconsistency doesn't matter. (Of course I might be wrong about that.)

Keen to hear your thoughts on this @jesseduffield.

**Comment by jesseduffield** [comment]
I say we should retain the escape key for canceling a non-sticky range selection. And not just for consistency: the main reason for me is that often I want to cancel the range but retain the currently selected index and I don't like having to move my cursor down then back up again in order to do that. Admittedly, I can use the 'v' key for this, but given that I never use sticky range select, it feels much more natural to use the escape key.

**Comment by jesseduffield** [comment]
I think it would feel jarring if that happened: often you want to select a range, perform an action, then move onto the next range to select (e.g. when staging various files), and having to hit down twice would be awkward

**Comment by stefanhaller** [comment]
Hm, ok. Seems like I have to get used to the extra esc presses, then.
