### ISSUE TITLE
How do I install this on Debian?

### ISSUE THREAD

**Issue by digitalbaboon** [jesseduffield/lazygit#330]
I have tried doing what the Ubuntu description says, but it gives me the following:

```
$ sudo add-apt-repository ppa:lazygit-team/daily
 
 More info: https://launchpad.net/~lazygit-team/+archive/ubuntu/daily
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp_y1oyn1b/pubring.gpg' created
gpg: /tmp/tmp_y1oyn1b/trustdb.gpg: trustdb created
gpg: key 68CCF87596E97291: public key "Launchpad PPA for lazygit-team" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.browser'
```

**Comment by mjarkk** [comment]
You could use a prebuild from the releases: 
1. Download the latest build from [here](https://github.com/jesseduffield/lazygit/releases)
2. Extract the .tar.gz and extract the .tar file that's inside it
3. copy over lazygit to /usr/bin `sudo cp lazygit /usr/bin/`

**Comment by digitalbaboon** [comment]
Thank you! @mjarkk

**Comment by rayluo** [comment]
@jesseduffield your project is featured in the articles pushed to my Android phone today. Nice project!

One quick suggestion though, from me as a new user who spend quite some time unsuccessfully trying to install lazygit into my non-mainstream Linux distro.

* Move that "[Binary Release (Windows/Linux/OSX)](https://github.com/jesseduffield/lazygit#binary-release-windowslinuxosx)" section to a higher place (because `sudo apt-get install lazygit` emits errors - there is [another issue](https://github.com/jesseduffield/lazygit/issues/385) on this already).
* Your latest 0.17 release does not contain binary builds. You probably need to somehow automate that build process so that it would not be forgotten. :-)

Again, thanks for such a promosing project. I'll definitely play with it more!

**Comment by dariogriffo** [comment]
You can install it using 
https://github.com/dariogriffo/lazygit-debian

**Comment by rayluo** [comment]
Nowadays I just settle on downloading the official binary from the [latest official releases](https://github.com/jesseduffield/lazygit/releases), and extract it into somewhere inside my local PATH.

**Comment by jmkim** [comment]
From August 2025, Debian 13 _"trixie"_ or Ubuntu 25.10 _"Questing Quokka"_ onwards, you may simply run `sudo apt install lazygit`.

https://github.com/jesseduffield/lazygit#debian-and-ubuntu

Sorry for the noise; this issue has been closed for a long time, but since it still appears high in search results, I am commenting here.

**Comment by dariogriffo** [comment]
yes, you can download it from official repos. yet still quite outdated

<img width="1377" height="330" alt="Image" src="https://github.com/user-attachments/assets/c9907f54-514f-4cff-be97-c7f97a76ea33" />

**Comment by jmkim** [comment]
Hi @dariogriffo, thanks for pointing that out.

It is intentional, so it will remain outdated. We can refer to [_Debian FAQ 3.1.3: The stable distributions really contains outdated packages._](https://www.debian.org/doc/manuals/debian-faq/choosing.en.html#s3.1.3)

At the time of [the Trixie freeze (May 15, 2025)](https://release.debian.org/trixie/freeze_policy.html), version [0.50.0 was the latest available](https://github.com/jesseduffield/lazygit/releases/tag/v0.50.0). It will not be updated until the next Debian release (Forky), unless you use [Trixie backports](https://backports.debian.org/Instructions/).

**lazygit is not in Trixie backports yet.** I will try to get the latest version into the Trixie backports within a month or so.

Meanwhile, in Debian Testing and Debian Unstable, lazygit is already up to date (currently 0.57.0). https://tracker.debian.org/pkg/lazygit

**Comment by dariogriffo** [comment]
> Hi [@dariogriffo](https://github.com/dariogriffo), thanks for pointing that out.
> 
> It is intentional, so it will remain outdated. 

Yes I know and that's why I created my mirror 😉
And I can tell you more than half of the traffic in my mirror is bookworm

**Comment by jmkim** [comment]
> And I can tell you more than half of the traffic in my mirror is bookworm

Good to know!
