### ISSUE TITLE
Tree takes too long to generate

### ISSUE THREAD

**Issue by glvr182** [jesseduffield/lazygit#339]
**Describe the bug**
It's not a bug, it's more or less a performance issue. When you take a huge (and i mean huge) git project, (for example the linux kernel), it takes ages to render the tree and if you switch to a different branch it will display properly because it's still rendering (It's not my hardware, I'm running it on a high end machine).

**To Reproduce**
1. Open a big repo
2. Render the tree by going over a branch
3. Switch branches a few times and see the result

**Expected behavior**
The tree to be rendered properly in an acceptable time.
This might be done by limiting the trees length and increasing it when the user presses page down.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Lazygit Version: The latest

**Comment by jesseduffield** [comment]
Just did some investigating: turns out limiting the number of commits returned actually makes no difference (at least on my end). What _does_ make a difference is removing the `--graph` arg. It looks like we might need to make a call and remove that arg. I'm not sure how much value people currently get out of it though.

**Comment by jesseduffield** [comment]
turns out if you get git v2.18 and do this:
```
git config --global core.commitGraph true
git config --global gc.writeCommitGraph true
cd /path/to/repo
git commit-graph write
```

You can actually speed up these graphs by a lot. And with that configuration, reducing the number of commits shown to 10 down from 100 we actually do see an additional performance gain so looks like that change, along with some lazy-loading, would be a good fix.

Only issue is that it requires git v2.18 haha

**Comment by glvr182** [comment]
Interesting, yeah the 2.18 requirement sucks, what we could do is on startup check the version of git. If the version is compatible, set a certain flag which will change the way the graph is loaded. If it is not compatible, we could use the legacy --graph option. I am not that big of a fan of removing the graph feature, since we do not know how many people are using it.

**Comment by mjarkk** [comment]
Lazygit could also check for the amount of commits. If that's higher than a specific number it won't show the graph.  

What we could do is give the option to load the graph manually when there are more than for example 2000 commits and the git version is less than 2.18. It could show a message like: `graph is to big to auto load Press 'l' to load it`
