### ISSUE TITLE
Can no longer push to pull request branches

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#3588]
https://github.com/jesseduffield/lazygit/assets/191335/f5e89ef6-8ac5-43e2-84e9-6d5713b0a5ec

Note that `git push` works (end of video) but lazygit reports diverged remote / stale info and fails to (unnecessarily) force push.

This is for a branch created using `gh pr checkout` on a remote which is not present locally.

In the repo's git config, it looks something like this:

```
[branch "daily-challenge"]
	remote = https://github.com/bdach/osu-server-spectator.git
	pushRemote = https://github.com/bdach/osu-server-spectator.git
	merge = refs/heads/daily-challenge
```

```
❯ lazygit --version
commit=, build date=, build source=homebrew, version=HEAD-0fbed71, os=darwin, arch=arm64, git version=2.45.1
```

**Comment by stefanhaller** [comment]
Did this work in 0.40.2? My suspicion is that it did, but only as long as you didn't have to force-push. Any attempt to force-push would have resulted in the same "stale info" error.

For context, there are two PRs that broke this workflow in different ways. The first is #3387, which removed the logic to ask for force-pushing when the server rejected the push. We still need this logic for branches whose upstream is not stored locally, because in that case we can't tell ahead of time whether force-pushing is going to be needed. The second is #3528, which would always ask for force-pushing if the branch shows a `?`. This is wrong, we need to start with a normal push in that case, and then only ask for force-push if the server rejected it.

Fixing these two problems (or actually, just the second) will make it work again if a normal push is sufficient. However, it will still not fix the "stale info" error that you get when you do in fact need to force-push, and I suspect that this problem was always present for such branches. It is caused by the `--force-with-lease` argument that lazygit uses to force-push; I think this will have to be just `--force` in the case that the remote branch is not stored locally.

Draft PR is here if you want to test it: #3619. It fixes the two problems mentioned above, but not the "stale info" problem yet. Just wanted to confirm my theories before I spend more time on this.

**Comment by stefanhaller** [comment]
I did some more testing and concluded that force-pushing to a branch whose remote is not stored locally can never have worked. I updated #3619 to fix that problem too.

**Comment by peppy** [comment]
>  However, it will still not fix the "stale info" error that you get when you do in fact need to force-push, and I suspect that this problem was always present for such branches.

Can confirm this was the case. I just force push to these kinds of branches quite rarely, and when I do I use the CLI execute window in lazygit 😄.

I've tested your fix at a functional level and it fixes the problem. Thanks again.
