### ISSUE TITLE
Can I change delay after hitting Escape key?

### ISSUE THREAD

**Issue by seven1m** [jesseduffield/lazygit#3669]
**Topic**

I absolutely love Lazygit and have integrated it to my daily workflow. One minor gripe I have is the delay you get between pressing Escape and Lazygit backing out of the current thing.

It feels like it’s about a second. I think it’s this thing: https://superuser.com/questions/1579208/delay-after-hitting-escape

**Your thoughts**

Is this normal? Is it just my machine? My terminal? I don’t have this when using Neovim (which uses Escape a lot) — only in Lazygit.

Thanks so much for such a wonderful tool! It has absolutely revolutionized how I work with git. ❤️❤️❤️

**Comment by stefanhaller** [comment]
For what it's worth, I don't have this delay. Pressing escape in lazygit is pretty much instantaneous for me.

Looking at [the tcell code](https://github.com/gdamore/tcell/blob/88b9c25c3c5ee48b611dfeca9a2e9cf07812c35e/tscreen.go#L1832), it seems lazygit uses a hard-coded 50ms timer for escape detection which is not configurable. So the delay you are seeing must be caused by something else, I'd say.

Did you try different terminal applications?

**Comment by seven1m** [comment]
Thank you for that! Good to know it might just be something on my end.

I see this in iTerm and on Termius on my phone. I will try other terminals and without any dotfiles loaded.

**Comment by seven1m** [comment]
I found one source: tmux's `escape-time` setting. I bet iTerm has a setting too, which I will check later. I think my problem is solved now. Thank you!
