### ISSUE TITLE
when making a gpg signed commit, lazygit minimizes and you are shown the output of the git commit command and asked to press enter to continue

### ISSUE THREAD

**Issue by Un1q32** [jesseduffield/lazygit#3700]
**Describe the bug**
I just setup signed commits and now lazygit minimizes itself every commit, I can still use it just fine it's just annoying

**To Reproduce**

1. Setup signed commits with git
2. make a commit with lazygit

**Expected behavior**

**Screenshots**
![image](https://github.com/jesseduffield/lazygit/assets/57970114/c7a09769-ba40-4f21-b0fc-567ebf7c7440)

**Version info:**
`commit=, build date=, build source=unknown, version=0.42.0, os=linux, arch=amd64, git version=2.45.2`
`git version 2.45.2`

**Comment by Un1q32** [comment]
Just tested with the latest master, still happens

**Comment by stefanhaller** [comment]
This is not a bug. Lazygit does this because it has no way of knowing whether you will be required to type a password. Minimizing itself is the only way it can let you do that if you need to.

If you know you never need to type a password (because you have some kind of password agent), you can add this to your lazygit config to avoid this:
```yaml
git:
  overrideGpg: true
```
