### ISSUE TITLE
Don't show scrollbars when the entire content is visible

### ISSUE THREAD

**Issue by jakubkaczor** [jesseduffield/lazygit#3772]
**Is your feature request related to a problem? Please describe.**
Scrollbar indicates to me there is something to scroll, especially if it doesn't fill the entire space. Oftentimes, there is nothing to scroll.

**Describe the solution you'd like**
I would like the scrollbars to show only if there is something to scroll.

**Additional context**
![image](https://github.com/user-attachments/assets/ead59000-e55c-40e2-bad0-a8fe4a33543f)

**Comment by stefanhaller** [comment]
Scroll-bars do disappear when there's really nothing to scroll, this works correctly already. In your case, there _is_ something to scroll (try it by using the mouse wheel or pressing ctrl-d: it will scroll down a few lines).

This is caused by the config option `gui.scrollPastBottom`, which is true by default. This is causing lazygit to make the text a little longer than it actually is. I personally hate this option and have turned it off (in VS Code as well, which has a similar option).

@jesseduffield Would you consider changing the default of this config to false?

**Comment by jesseduffield** [comment]
I personally love the option because it allows me to view each line at of code at whichever position on the screen is most comfortable for me to read (typically the centre). I don't see the need to change the default, but am open to doing so if more people complain

**Comment by stefanhaller** [comment]
I see; I wasn't aware that that's the reason for the option to exist. I thought it's so that you don't lose track of where you are when you scroll by whole pages. Anyway, happy to keep the default the way it is if you prefer it.

The thing is that I don't think people will complain about it. I suspect most people aren't conscious about the option, or whether it's ideal for them. I have a coworker with whom I pair a lot, and whenever he wants to see the last page of a diff, he will scroll down quickly, overshoot a lot, and carefully scroll up again until he sees enough of that last page. It's painful to watch every time; it would be so much easier if he could just fling downwards until he hits the end. I tried to talk to him about it and persuade him to turn that option off, but he didn't see a problem.

**Comment by jakubkaczor** [comment]
Thank you, stefanhaller. I read the configuration and `gui.scrollPastBottom` didn't seem relevant, but it actually does what I need and solves the issue.

> Scroll-bars do disappear when there's really nothing to scroll, this works correctly already.

Right, it disappears with the option turned off. Perhaps the title of this issue is more precise than a description. I meant not to show the scroll bar when the entire diff content is already visible.

If it comes to the defaults, I only want to note that the behavior with `gui.scrollPastBottom = false` is default in Firefox and likely in other web browsers, so it may be more expected for an average user.
