### ISSUE TITLE
Add feature of display committed file list

### ISSUE THREAD

**Issue by skanehira** [jesseduffield/lazygit#383]
**Is your feature request related to a problem? Please describe.**
No.
This is just feature request.

**Describe the solution you'd like**
Implement feature of committed files.

**Describe alternatives you've considered**
Add menu and shortcut in Commits panel

**Additional context**
Nothing.
I'll try implement this feature.

**Comment by jesseduffield** [comment]
awesome :) 

I've been thinking about this too: I think we should make it so that if you hit 'enter' on a commit, the commits panel goes from showing commits to showing the list of files in the selected commit, and then when you select each file, it shows the file in the main view. Then when you hit 'esc' it returns back to the regular commit view.

I've implemented a concept of 'contexts' which enable you to have different keybindings on a given view with different contexts. For example, in the 'merging' context, the main view has different keybindings to when it's in the 'staging' or 'normal' contexts.

I think that could be used here, although there's no real pattern yet for displaying different things based on different contexts, but I don't think it would be that complicated. Let me know if you have any questions :)

**Comment by skanehira** [comment]
>I've been thinking about this too: I think we should make it so that if you hit 'enter' on a commit, the commits panel goes from showing commits to showing the list of files in the selected commit, and then when you select each file, it shows the file in the main view. Then when you hit 'esc' it returns back to the regular commit view.

I cloud grasp your image.
Thank you :)

>I've implemented a concept of 'contexts' which enable you to have different keybindings on a given view with different contexts. For example, in the 'merging' context, the main view has different keybindings to when it's in the 'staging' or 'normal' contexts.

I have not understood the source code yet, so I think i'll try development it first, is it good?

**Comment by jesseduffield** [comment]
yep, go ahead :)

**Comment by skanehira** [comment]
@jesseduffield 
I try developed and it seems like worked.

![Mar-09-2019 18-29-28](https://user-images.githubusercontent.com/7888591/54069231-554c3d00-4299-11e9-8285-bc0203077783.gif)

**Comment by jesseduffield** [comment]
awesome! Put up a PR and I'll give it a review :)

**Comment by jesseduffield** [comment]
closing because @skanehira 's PR is now merged. Thanks again :)
