### ISSUE TITLE
Shell commands no longer run from the current repository directory

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#3872]
Regressed at some point, used to work. Testing on current HEAD (05ae080)

![iTerm 2024-08-29 at 05 01 04](https://github.com/user-attachments/assets/cbd32151-c683-4bcf-b63c-ccf6f2b38fb0)

**Comment by stefanhaller** [comment]
Can't reproduce, seems to work correctly for me. Could you provide more detail? From which directory are you starting lazygit, and what is the path to your repo? This is hard to see from the video.

**Comment by peppy** [comment]
Sorry, here's a more clear video:

https://github.com/user-attachments/assets/fa0ed64c-4fee-4cab-8623-209a91deb6b8

I'm starting lazygit from `~/Projects` and the repo here is `~/Projects/osu`.

May be something to do with my shell being fish, but it did work until recently and I don't believe I've changed anything at my end.

**Comment by stefanhaller** [comment]
It's probably caused by #3793 then. Does your `config.fish` cd to `~/Projects`? That would explain it.

**Comment by peppy** [comment]
Yes, it does 😅, sorry I forgot that's how I had things setup:

```
if status is-interactive
    cd ~/Projects
end
```

I wonder if I can implement a solution in my config in that case.

**Comment by stefanhaller** [comment]
We have no way to customize the shell that is being used for custom commands. We were hoping that calling `$SHELL -i` would always work well, but here's one case where it doesn't.

One potential workaround could be if lazygit would set an environment variable (e.g. `LAZYGIT_CUSTOM_COMMAND=1` or some such) which you could then check in your config file.

But my recommendation would be to remove it from your config file, and instead configure your terminal so that it cds to Projects when you open a new tab. Most terminals have such an option, I think.

**Comment by peppy** [comment]
I think the reason I set it up this way was for `ssh` sessions to also get the correct default directory. But I seldom use that so I will take your advice for now.

Thanks!
