### ISSUE TITLE
Async Discarding

### ISSUE THREAD

**Issue by antdon** [jesseduffield/lazygit#4007]
### Suggestion Description
I have found that in large code bases discarding a single line change freezes the client until it has finished. This is something I do all the time. Before committing I like to go through my change line by line and either add or discard them. 

### Potential Solution
It looks like this is creating a patch file with the change and then reversing it. This is a lot to be doing synchronously. I think it would be cool if this was done asynchronously with a cute spinner the way committing is done. 

I looked into the code to see how easy a change this would be. Without actually debugging to check my theory, it seems to be the handleDeletePatchFromCommit method that is responsible for this. 
I guess you have some way of doing this for the commit command. If you think that this could work I will investigate how you do that and follow suit. 
It would be really nice if we displayed the line differently as it is discarding or something... maybe a little bin emoji.

**Comment by mark2185** [comment]
As a workaround, have you tried _addding_ those lines you wish to stage, and leaving those you don't as is, and then discarding all unstaged changes from the file?

**Comment by stefanhaller** [comment]
Discarding a single line should be very fast even in large repositories. If this is slow for you, I suspect you might be running into what was discussed here: https://github.com/jesseduffield/lazygit/discussions/3965#discussioncomment-10841236

Could you try the suggestion there and see if this makes a difference?

Doing it asynchronously would be rather tricky, because when you want to perform the next action (staging or discarding another line), lazygit needs the up to date state of your files, but doesn't have it while the previous command is still running. That's the reason we're doing it synchronously. I'm not saying it can't be done with some clever optimistic updating of our state, it would just make the code much more complex and harder to maintain.

**Comment by antdon** [comment]
Yeah I tried #3965. Didn't help much. Still has about a 3 second lag for each operation. 
I don't know if other git clients are doing the optimistic updating you are describing but this isn't a problem that's shared by everyone. I migrated from fork and found their discarding to be instant.
I admittedly didn't consider keeping track of the state of the file while we are doing these things and that does make it a more tricky problem. We have got that patch file with the changes we are making, maybe we can indicate that that line or file is being operated on and can't be further operated on until the patch has been applied? I also don't even know that you have to allow multiple operations to queue up, you can prevent further git commands until the current one is finished, but pausing the UI until a git command is done feels really bad. 
Anyway, it will be a fair bit of work to only benefit people who work on really large repos so I understand if you don't want lazygit to undertake this.
