### ISSUE TITLE
Crash after quitting editor

### ISSUE THREAD

**Issue by aragon999** [jesseduffield/lazygit#403]
**Describe the bug**
Sometimes after I finished editing a file (in `vim`) and save with `:x` Lazygit crashes with the following message:
```
*errors.errorString invalid point
/.../lazygit/vendor/github.com/jesseduffield/gocui/view.go:190 (0x56062e99e85f)
/.../lazygit/pkg/gui/view_helpers.go:187 (0x56062ebd1ab3)
/.../lazygit/pkg/gui/files_panel.go:66 (0x56062ebb0114)
/.../lazygit/pkg/gui/view_helpers.go:93 (0x56062ebd0dcc)
/.../lazygit/pkg/gui/view_helpers.go:164 (0x56062ebd171c)
/.../lazygit/pkg/gui/gui.go:453 (0x56062ebb61a2)
/.../lazygit/vendor/github.com/jesseduffield/gocui/gui.go:353 (0x56062e99c992)
/.../lazygit/vendor/github.com/jesseduffield/gocui/gui.go:469 (0x56062e99d214)
/.../lazygit/vendor/github.com/jesseduffield/gocui/gui.go:377 (0x56062e99cbc6)
/.../lazygit/pkg/gui/gui.go:593 (0x56062ebb8959)
/.../lazygit/pkg/gui/gui.go:602 (0x56062ebb8ac1)
/.../lazygit/pkg/app/app.go:130 (0x56062ebdcbdd)
/.../lazygit/main.go:51 (0x56062ebdd57a)
/usr/lib/go/src/runtime/proc.go:200 (0x56062e3deb94)
    main: fn()
/usr/lib/go/src/runtime/asm_amd64.s:1337 (0x56062e409b11)
    goexit: BYTE    $0x90   // NOP
``` 

**To Reproduce**
1. Edit a file from the "file view" via `e`
2. Do your editing
3. Save the file and quit back to lazygit
4. See sometimes an not clearly reproducible error

**Expected behavior**
After saving the file and quitting the editor, one should be back in the `lazygit` tui

**Screenshots**
Probably not needed. 

**Desktop (please complete the following information):**
ArchLinux: `commit=63e2ccfccf32bd7fff2e721940f8173c6194cce5, build date=2019-03-12T17:13:18Z, build source=binaryRelease, version=0.7.2, os=linux, arch=amd64`

**Additional context**
\-

**Comment by jesseduffield** [comment]
I was able to reliably reproduce this by adding a heap of files, scrolling down beyond the bounds of my files panel to the last file, then editing it. We crash upon return because when re-selecting the file, the logic that handles whether we need to scroll the files panel or not looks at the view rather than the mode. The view hasn't yet rendered so it things there's no items meaning it doesn't need to scroll, but we're telling it to focus on item e.g. 20 (when the height of the view is e.g. 10). So it crashes due to the invalid point.

I've put up a PR https://github.com/jesseduffield/lazygit/pull/404 to fix this FOR ONCE AND FOR ALL

**Comment by jesseduffield** [comment]
If you check out the latest master, this issue should be resolved :)

**Comment by aragon999** [comment]
I can reproduce the error as well, and seem to remember, that it (probably) was the last file in the view, when lazygit crashed. Yesterday I checked for common patterns more in the files not the view :-)

I can also confirm, that with #404 the problem is fixed. Thank you for the quick response and fix.
