### ISSUE TITLE
[Request]Search commit message from many commits.

### ISSUE THREAD

**Issue by skanehira** [jesseduffield/lazygit#407]
**Is your feature request related to a problem? Please describe.**
Not any problem, this is just a request.

**Describe the solution you'd like**
When user has so many commits, it is hard to find a specific commit.
I think the feature of search commit message can be helpful for many users.

**Describe alternatives you've considered**
Implement feature of search of commit message from many commits.
When user press `Ctrl + f` on Commits panel, search window will pop up.
When input any word, then search will start and display result in Commits panel.

**Additional context**
I'm troubled about search interface.
Create search window?  or new panel?
Please tell me your thoughts

**Comment by prosoitos** [comment]
I agree! I just transitioned from tig to lazygit and I am very impressed by lazygit.

The one thing that I am missing are search functionalities: ability to run `git-grep` to search within files and ability to search within commit messages.

**Comment by jesseduffield** [comment]
@prosoitos @skanehira I'm going to find some time to work on this feature soon. I haven't spent much time with tig but it looks like the following is how it works in tig:

you press '/' and then type your string, and then after hitting enter you use 'n' and 'N' to cycle through the results. If the string doesn't appear on the first commit line, it won't match. Is that the gist of what we want here?

I like the idea of doing this is in a view-centric way, because it means I can easily roll out the same behaviour to other panels. But that means not being able to do smart things like check for the string in multi-line commit messages (because the string may not actually appear in the panel). What are your thoughts?

**Comment by jesseduffield** [comment]
I've got a PR up for this now. Please let me know your thoughts :) https://github.com/jesseduffield/lazygit/pull/659

**Comment by prosoitos** [comment]
Thank you again for looking into this so very quickly!!

This looks great.

About your comment above: would this be implementable also on the right (view) panel? If so, this would also make multi line commits searchable. But I guess that view panel functions very differently than the side ones and this may not be easy to do.

**Comment by prosoitos** [comment]
And I think that you are correct about tig: as far as I can tell, there is currently no way to search into multiple line commits. So what you just implemented does (I think) bring to lazygit the same level of functionality when it comes to searching.

**Comment by prosoitos** [comment]
In another issue I opened yesterday, I suggested a few other features. One of them is to allow to run git commands in lazygit, for instance with `:` (as tig and other applications do).

With this implemented, then one could of course run `git log --all --grep="<pattern>"`.

But there may be neater ways to do this.

One such way, if not a nightmare to implement, might be to be able to toggle panel 4 to show the entire commit message???

**Comment by prosoitos** [comment]
> I've got a PR up for this now. Please let me know your thoughts :) #659

I like that this works also for the files panel :slightly_smiling_face:

**Comment by jesseduffield** [comment]
> About your comment above: would this be implementable also on the right (view) panel?

I would like to add this, but it will take a bit more effort. We don't really have a way of saying 'focus the main view' as we do in lazydocker (a similar program). Usually when the main view is focused, it's because we're e.g. staging a file line by line, and in this context it's actually a little tricky to switch between staging mode and searching mode. Suffice it to say, this will need to be covered in a separate PR :)

> One of them is to allow to run git commands in lazygit, for instance with :

Had I known this was a convention when I made lazygit I would have made `:` the keybinding for it, but currently you can run a custom command with `shift+X` in the files panel. Unlike in tig, this will swap over to a subprocess to run the command, in case user input is required. This has the convenient benefit of allowing you to make use of the existing search functionality in your pager for commands like `git log -p`. I'll actually put up a PR to add ':' as a keybinding for this as it makes intuitive sense (though for now we'll retain the popup panel over the bottom-left position approach)

I think that with that custom command functionality, many of the search use cases are covered, because you can search within the pager of the custom command. But I am certainly open to ways in which we could facilitate more use-cases 'in-house'.

**Comment by jesseduffield** [comment]
I've just merged the PR that satisfies the original use case of this issue so I'm going to close it: https://github.com/jesseduffield/lazygit/pull/659

If we want to see any expanded functionality with respect to searching commits, please create a new issue :)

**Comment by prosoitos** [comment]
> Suffice it to say, this will need to be covered in a separate PR :)

No problem!

> currently you can run a custom command with shift+X in the files panel

Ah! Sorry I missed that. I hadn't realized that the functionality was already implemented.

> Had I known this was a convention when I made lazygit I would have made : the keybinding for it

I don't think it is a convention, so you can choose whatever binding you like :slightly_smiling_face: It is just used by many programs (e.g. ranger, tig, zathura).

> I think that with that custom command functionality, many of the search use cases are covered,

Yes: totally! This functionality covers pretty much everything :smile:

**Comment by prosoitos** [comment]
Just tried the new search functionality: it is GREAT!

Thank you!!! :slightly_smiling_face:
