### ISSUE TITLE
LC_CTYPE ignored when outputting to terminal

### ISSUE THREAD

**Issue by h3xx** [jesseduffield/lazygit#422]
**Describe the bug**

Using Lazygit on any terminal that describes itself in the standard way as `LC_CTYPE=C` (8 bit output) results in 16-bit Unicode output.

**To Reproduce**

1. Run `LC_CTYPE=C lazygit` to request 8-bit output compatible with an 8-bit character display 

--> Result is screaming terminal due to 16-bit Unicode characters being output.

**Expected behavior**
Use either ASCII graphics or IBM alt graphics mode.

**Desktop (please complete the following information):**
 - OS: Slackware Linux 14.2
 - Lazygit Version 0f1abcb10c7ccef2ec287583ea790173c895ae33

**Additional context**

Installed using `go get` command described in README.md

**Comment by mjarkk** [comment]
I've tried to get the same *creaming* output but whatever i try all terminals seems to have 16bit support.  

Do you know a way to get the same result in a normal linux distro with gnome?  
I can try to remove all 16 bit color but it's a bit hard to debug without the same result as you.

**Comment by fluff** [comment]
I'm having the same issue on MacOS with Terminal.app configured to use ISO-8859-1 and LC_CTYPE set to a locale with ISO-8859-1, for example `export LC_CTYPE=en_US.ISO8859-1`. (This is not the default, but I use it frequently when interfacing with machines whose file system is full of legacy ISO-8859-1 file names and contents)

Note that this has nothing to do with 16bit colors, I think. 

It's about using an 8bit character set instead of UTF-8; it seems lazygit outputs UTF-8 characters even when the terminal and the LC_CTYPE variable indicates a preference for a non-UTF-8 character set like ISO-8859-1. Midnight Commander, for example, does respect this setting and is able to draw "line art" characters even with this reduced character set).

**Comment by jesseduffield** [comment]
this issue might be related (gocui is the library we use under the hood) https://github.com/jroimartin/gocui/issues/139

**Comment by jesseduffield** [comment]
I've put up a PR for this https://github.com/jesseduffield/lazygit/pull/552
Could you give that ago @fluff or @h3xx ?

**Comment by jesseduffield** [comment]
@fluff @h3xx could either of you see if this PR fixes the issue? https://github.com/jesseduffield/lazygit/pull/1490

**Comment by jesseduffield** [comment]
Closing this issue because I'm confident that the linked PR will resolve the issues but if not lemme know and I'll reopen
