### ISSUE TITLE
NOISSUE - Titles, labels and milestones

### ISSUE THREAD

**Issue by glvr182** [jesseduffield/lazygit#427]
As the title states this is not an issue, it is more or less a thread I want to start to talk about possible use of labels, titles and milestones. I had this idea, checking out projects like [mainflux](https://github.com/mainflux/mainflux) to use labels and titles to indicate what the issue or pull request is all about.

The issue titles would be:
 * NOISSUE - Title of an issue that is just for discussion.
 * BUG - Title of an issue that represents a bug.
 * FR - Title of an issue that represents a feature request.

The PR titles would be like: 
 * LG-123 - Title of a PR fixing issue 123.

If the PR is a WIP you can tag it as a "draft" using [this](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

Labels would be like:
 * needs comment
 * gocui
 * git
 * config
 * core
 * urgent

The milestones would be representing releases like:
 * x.y.z

I hope to get lots of feedback on this! Let me know what you think!

**Comment by mjarkk** [comment]
I'm not sure if this is a good idea.  

Personally i would prefer the builtin labels over a title prefix.  
Some times that labels have:  
- Easier to spot due to there color.
- Easier to filter because someone can just click on one and see what's going on.
- A random person from the internet doesn't have to add a prefix. The more information you need to fill in to create a issue the more people think whatever i'm not going to do all this work to create a feature request.

Here are a just a view projects that use them actively:
- [vscode](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [parcel](https://github.com/parcel-bundler/parcel/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [bat](https://github.com/sharkdp/bat/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

@jesseduffield Could give a view maintainers the right to add labels and all issues are nicely labeled :)

**Comment by glvr182** [comment]
I also prefer the labels, but problem lies with the label permission, he would have to give maintainers that permission.

**Comment by mjarkk** [comment]
Ow i see the problem, I thought it was possible to give users some permissions to for example change the labels but that's not possible 😞. That must have been Gitlab then..  
I was just searching for some bot that might be able to do that but such a thing doesn't seems to exists yet.

**Comment by glvr182** [comment]
@mjarkk thats too bad... im gonna keep looking at the github docs to see if there are options besides this..

**Comment by glvr182** [comment]
After checking the docs I found [this](https://help.github.com/en/articles/permission-levels-for-a-user-account-repository). So in short you have to have all the permissions if i'm not mistaking.

**Comment by skanehira** [comment]
@glvr182 I think it's good idea :)

**Comment by jesseduffield** [comment]
turns out you can set labels in the issue templates, so I added labels to the respective templates, and added a 'discussion' template.

As for milestones, I agree that we should start getting into the habit of grouping things up into versions and maybe even seek regular releases.

**Comment by glvr182** [comment]
Nice that helps a lot!

I am totally for the grouping and issue - PR linking (every PR needs an issue). Also how regular would u see the releases, weekly? monthly or something else?

**Comment by glvr182** [comment]
Closing this
