### ISSUE TITLE
Scrolling through big commits really slow

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazygit#435]
**Describe the bug**
The application hangs when scrolling between commits that are really big.

**To Reproduce**
1. Create a git repo
2. Commit a lot of files for example the vendor folder or node_modules
3. Do that a view times
2. Open lazygit and go to the commits tab
3. Try scrolling through commits

**Expected behavior**
The commit might take longer to load but the application still needs to run smooth.

**Desktop (please complete the following information):**
 - OS: Solus 4 (linux)
 - Lazygit Version: [This branch #372](https://github.com/jesseduffield/lazygit/pull/372) (it's up to date with master)

**Comment by jesseduffield** [comment]
This is a tough one. After looking through the docs, I can't find any way to limit the output of the `git show` command. It seems like the only option we really have is to obtain the list of changed files, then file-by-file, append to the output until we've filled one page, and then fill the remaining pages if the user decides to scroll. But that does sound fairly complex.

I'd also be interested to know if it's slow because it takes a while to fetch the data, or if it's because it takes a while to render the data in the view. If it's the latter, we can just not write any more text into the view than we need to, until the user scrolls.

**Comment by mjarkk** [comment]
Network activity is 0b/s while scrolling over commits

**Comment by matthew-nm** [comment]
I have encountered this issue as well, my lazygit reaches 100% cpu usage for quite a long time whenever I enter the "commits" box for a particular project which has a few large commits. The time it takes to render the `git show` output in lazygit takes much longer than it does to do a `git show >> file.txt` in the terminal, making me think that the slowdown comes from the rendering.

And in turn, the `git show >> file.txt` command in the terminal takes a lot longer (relatively) compared to `git show` in the terminal, which immediately opens a pager. Idk anything about how lazygit works, but I assume it doesn't use a pager?

Also, this same issue comes into play in the "Files" box if I scroll down to the bottom of the listed files after creating the 'test.txt' file. I believe lazygit is trying to add the newly created file and again spends a lot of time opening and rendering. The cpu usage is again 100% during this slowdown. Removing this file eliminates the slowdown within the "Files" box.

I am hoping to use lazygit full-time, so please let me know what I can do to help characterize this slowdown!
