### ISSUE TITLE
Using cobra as the argument parser.

### ISSUE THREAD

**Issue by glvr182** [jesseduffield/lazygit#436]
**Topic**
Right now we have an issue open #413 that requires us to parse a flag. We run/ran into troubles when we the arguments are formatted in a special way.

**Your thoughts**
We should use a library like [cobra](https://github.com/spf13/cobra) to make things easier for us to parse command line arguments. I think we should give it a try and see if it can make things easier for us.

**consequences**
We would have to rewrite the way lazygit starts up. And we might have to restructure the project a bit (see the cobra page) but after that we would be able to add commands and cli arguments to the project without any trouble.

Let me know what you guys think!

**Comment by jesseduffield** [comment]
I left a comment in the PR https://github.com/jesseduffield/lazygit/pull/414/files#r278800630 but didn't realise this issue was here. As I said in that comment, I reckon flaggy is a package which satisfies our needs here, and is very lightweight.

If we can find a use case where we really need cobra, I'm happy to use it, but until then I think we should try and stay as minimal as possible. Furthermore I actually think we should be trying to minimise support for command-line arguments, and try and keep things in the UI where we can be more user friendly. The original reason for having a cmd line argument for a repo directory was that you couldn't open lazygit outside a git repo to be able to jump to that directory, but I think that's an issue we could actually ultimately fix (down the line perhaps) inside the gui rather than requiring the command line argument.

**Comment by jesseduffield** [comment]
closing, happy to reopen if there's further points of discussion :)
