### ISSUE TITLE
Renaming file shrinks the Files list but the cursor doesn't follow

### ISSUE THREAD

**Issue by GuillaumeRochat** [jesseduffield/lazygit#494]
**Topic**
Whenever files are renamed, they end up listed twice because of the Deleted ones and the Added ones. Once both the Deleted and Added version of the files are staged, it becomes a Rename, which means rather than having 2 lines, we get only 1. When doing so, the cursor stays at the same position in regard to the Files box, but both the Deleted file and the Added file get moved down to be Renamed. It causes the cursor to be 2 lines lower in regard to its position relative to the file names.

![lazygit-cursor](https://user-images.githubusercontent.com/1949339/61959864-52c15a00-af92-11e9-9f8b-7397144ab64e.gif)

**Your thoughts**
Since the number of items in the list changes and the filename under the cursor is merged with another one to become a Rename, we cannot really do much to prevent the list from moving. 

The only behavior that could make sens is if the cursor follows the list moving and end up being on the item below its original position. For instance, when I select the file `11` and below it there's `12` and then `13`, the cursor could end on `12` rather than `13`. It would mean moving the cursor up once.

Would this behavior make sens? Could we even detect that situation and add that behavior?

**Comment by jesseduffield** [comment]
I agree, that is kind of annoying behaviour. Two things come to mind:
1) We can use the `--no-renames` arg with git status so that it doesn't actually doesn't combine the deleted old file and added new file into a single line. That's trivial to implement, but then we lose the expressiveness of seeing that we have indeed renamed the file.

2) Instead of trying to move the cursor, we can try and instead slot the new line into the cursor's current position. We already have some basic logic for preserving the order of lines if for whatever reason `git status` returns them in a different order. We could try and build upon that by saying that if we have a new line that starts with `R a -> b` and our cursor was just on 'a' or 'b', then we slot that in where the cursor is.

What are your thoughts?

**Comment by GuillaumeRochat** [comment]
1. I think it's better not to use the `--no-renames` arg, because it is still useful to see the renames.

2. That could work in most/all scenarios.

- Assume 'a' is already added and above the cursor, 'b' is on the cursor. If we add 'b' and it becomes `R 'a' -> 'b'`, putting it where 'b' was means that the line 'a' is removed, the whole list moves up by one because we removed a line, and the cursor ends on the next line.

- Assume 'a' is already added and below the cursor, 'b' is on the cursor. If we add 'b' and it becomes `R 'b' -> 'a'`, putting it where 'b' was means that the line 'a' is removed, the whole list stays in place because we removed a line below, and the cursor ends on the same line.

Would that be the behavior we'd get from the 2nd solution?

**Comment by jesseduffield** [comment]
Yep! (sorry for late reply!)

**Comment by GuillaumeRochat** [comment]
@jesseduffield No worry.

Do you have any pointers on where to look for that in the code base, where the change could be done? I'm not sure when I could check it out but I might give it a try if I find some free time.

**Comment by jesseduffield** [comment]
@GuillaumeRochat sorry it's taken me so long to get around to this, I was going to give you some pointers but I was happy to continue on the back of a very similar issue I had just solved. This should now be resolved on master

**Comment by GuillaumeRochat** [comment]
@jesseduffield Amazing! Thanks for the update! I'll go read the PR for fun and I'll try it out.
