### ISSUE TITLE
Crash when merge conflicts are resolved

### ISSUE THREAD

**Issue by keksnicoh** [jesseduffield/lazygit#517]
**Describe the bug**
When a merge conflict is present, after adding the resolved files, lazygit shows the dialog "all merge conflicts resolved. Continue?". Unfortunately, the UI then hangs on this dialog and the process must be killed manually in order to stop it.

**To Reproduce**
1. Merge a conflicting branch
2. fix the issues
3. add the affected files 

**Expected behavior**
not crash

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Lazygit Version 0.8.2

**Additional context**
lazygit is awesome, thank you for doing this project!!

**Comment by glvr182** [comment]
Can you post the output from `lazygit -v` for me? Thanks!

**Comment by keksnicoh** [comment]
sure

`commit=, build date=, build source=homebrew, version=0.8, os=darwin, arch=amd64`

Best, Nico

**Comment by jesseduffield** [comment]
interestingly I've seen some similar behaviour recently with another person who was on v0.8. @keksnicoh do you get the same issue if you update to the latest version? If you've installed via homebrew's core repo you can get the latest lazygit using the tap by going
```
brew install jesseduffield/lazygit/lazygit
```

Also, does this problem occur every time or only sometimes? And if you try to complete the operation in the git command line directly, what message do you get? Is there any prompt for input?

**Comment by keksnicoh** [comment]
Hi, thanks for response. I updates lazygit, unfortunately lazygit still crashes when all merge conflicts are resolved.

`commit=, build date=, build source=homebrew, version=0.10.4, os=darwin, arch=amd64`

Best,
Nico

**Comment by jesseduffield** [comment]
@keksnicoh are you able to provide the stack trace the lazygit renders upon crashing?

**Comment by jesseduffield** [comment]
closing due to staleness

**Comment by bartgol** [comment]
I am having the same issue on my brand new laptop. Every time I use lazygit to solve merge conflicts during a rebase, it hangs while asking me if i want to continue (see screenshot attached).

Some info that can possibly help:
```
(bartgol) lbertag@s1072983:[bash_scripts (master)]$ lg --version
commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64
(bartgol) lbertag@s1072983:[bash_scripts (master)]$ conda list
# packages in environment at /home/lbertag/.conda/envs/bartgol:
#
# Name                    Version                   Build  Channel
lazygit                   0.32.2               ha770c72_0    conda-forge
(bartgol) lbertag@s1072983:[bash_scripts (master)]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.5 (Ootpa)
Release:	8.5
Codename:	Ootpa
(bartgol) lbertag@s1072983:[bash_scripts (master)]$ conda --version
conda 4.10.3
(bartgol) lbertag@s1072983:[bash_scripts (master)]$ python3 --version
Python 3.6.8
```

Obviously, now that I'm writing this it doesn't hang anymore. I will add a txt with the strace output next time it hangs. It 


![Screenshot at 2022-01-26 11-59-02](https://user-images.githubusercontent.com/3226046/151229605-8dbb7a04-f0d6-444e-9061-3920354693bc.png)

**Comment by bartgol** [comment]
Ok, I got another hang, still during a rebase, though not related to conflicts.

I was amending the second to last commit. The last commit had no conflicts with the amended files, so there was no conflict resolution. In the attached  screenshot, you see lazygit stuck, and at the bottom you can see it was working on the amendment.

As it was hanging, I straced lazygit, I'm attaching the output. I killed strace after a bit, since it seemed to repeat itself. I have no knowledge on how to analyze the strace output, so I can't tell if this is useful info or not.

![Screenshot at 2022-01-27 12-27-49](https://user-images.githubusercontent.com/3226046/151431030-d27c04b0-a7b4-4aa1-96d6-255f7caf9ffb.png)
[Uploading strace_lazygit_hang.txt…]()

**Comment by bartgol** [comment]
Ah, I think I might have another bit of info: I am actually using gpg signature, and I wonder if lazygit was stuck waiting for my gpg passphrase. I have `pinentry-mode loopback` in my gpg.conf, which, if I understand correctly that setting, makes gpg ask the caller for the pin. In this case, the caller might be a subprocess (I guess, I don't really know) of lazygit, but since I don't get to see the subprocess, everything gets stuck waiting for my gpg signature, without me even knowing (or having any chance to provide it).
