### ISSUE TITLE
Installation in Ubuntu 16.04 not working

### ISSUE THREAD

**Issue by retrofreak83** [jesseduffield/lazygit#61]
I follow the instructions as given, but the reaction is as follows: package lazygit cannot be found.

**Comment by jesseduffield** [comment]
As per the readme, please ensure `~/go/bin` is in your $PATH

**Comment by retrofreak83** [comment]
Yes, but this part of the readme refers to installation via go's get command. I tried the PPA variant. Meanwhile I took a look at the PPA that is online and discovered that the "Packages" files seem to be empty.

**Comment by jesseduffield** [comment]
Good point, I think I'll add a general 'installation troubleshooting' link that goes through all the common pitfalls.

I believe that empty packages file refers to external packages, which are now empty because we switched to bundling dependencies within the repo with Go's dep.

Did adding the path resolve your issue or is lazygit still not found by your system?

**Comment by retrofreak83** [comment]
What cannot be found is the *package* lazygit when I execute "apt-get install lazygit", not the command. So, ~/go/bin does not exist actually.

**Comment by jesseduffield** [comment]
ah right, I'm stuck thinking in Go-land, apologies. I'm guessing you've done each of the steps:
```
sudo add-apt-repository ppa:lazygit-team/daily
sudo apt-get update
sudo apt-get install lazygit
```
and the issue only occurs on the third step?

Maybe @dawidd6 can chime in here

**Comment by dawidd6** [comment]
Right, i was changing things according to these vendoring commits and i deleted all packages.

Sorry for inconvenience, it should be okay now.

**Comment by retrofreak83** [comment]
It is okay now, thanks alot!
