### ISSUE TITLE
cursor returns to start when creating custom patch

### ISSUE THREAD

**Issue by matejcik** [jesseduffield/lazygit#623]
**To Reproduce**
1. navigate to "Commit files" pane
2. pick a commit, press Enter to get to file list
3. pick a file, press Enter to go to patch editor
4. move a couple lines down
5. press \<Space\> to select the current line for patch

**Expected behavior**
The line is marked for patch (highlighted at start, shown in right pane), AND the cursor either moves to the next line, or stays on the same line.

**Actual behavior**
The line is marked for patch, but the cursor moves all the way up to start of file.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Lazygit Version 24e73cdd8b97ad2e1c6cd91cc35ee38ba4a49c70

**Additional context**
This started happening between v0.9 and v0.10.1, so there's not many things that could have caused it.

**Comment by jesseduffield** [comment]
Thanks for the detailed repo steps. To confirm, does the line move up to the top of the file (as in the very first line in the patch) or the first line starting with a +/-?

If it's the latter, I think this is the result of the staging panel and the patch panel sharing the same code for handling selections. In the staging panel you need some logic to go to the next stageable line because each time you stage a line the whole file needs to be reloaded so you lose your spot, whereas with the patch panel the file remains unchanged. I think this is a matter of pulling that logic out into just the staging panel and decoupling the code a bit

**Comment by matejcik** [comment]
It's the latter, first line starting with +/-. So you're probably right.

**Comment by matejcik** [comment]
seems to be fixed in current master?

**Comment by jesseduffield** [comment]
good enough for me! closing
