### ISSUE TITLE
File diff view doesn't show new lines on specific repository

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#634]
On only one of my repositories, when looking at unstaged/staged file diffs, the new lines are not visible. I've tested on two different terminal emulators.

![image](https://user-images.githubusercontent.com/191335/73897300-f805a500-48c8-11ea-9e94-3fc290e5b099.gif)

Note that the display is missing in the `osu-stable` repo until i enter line/chunk selection mode, while it displays correctly in the `osu` repo.

This is also the case when browsing commits in the log/history pane. Again, it works fine in all but this specific repo. Do I somehow have some repo-specific local config that lazygit is reading?

**Comment by jesseduffield** [comment]
I'm stumped. Is this repo publicly available?

IIRC whether we're loading the diff normally or for the line-by-line staging mode it's just getting a regular diff, so I've got no idea why those additions aren't appearing there in only one case.

**Comment by peppy** [comment]
unfortunately the one in question is private. let me do a bit of further testing with the repo (reclone) and see if i can come up with anything.

**Comment by jesseduffield** [comment]
Turns out the issue was that a carriage return character was present at the end of the line, and the gocui library (which lazygit uses) interpreted that as a command to clear the line rather than simply set the cursor to the start of the line. These characters usually show up when pushing code from a windows computer.

I've merged the PR https://github.com/jesseduffield/lazygit/pull/636 into the latest master, let me know if that fixes your issue :)

**Comment by peppy** [comment]
Fixed, thanks! Didn't think to check on line endings, makes sense.
