### ISSUE TITLE
Respect XDG_CONFIG_HOME on MacOS

### ISSUE THREAD

**Issue by cideM** [jesseduffield/lazygit#641]
**Is your feature request related to a problem? Please describe.**
This is about the only CLI utility I use which doesn't respect `XDG_CONFIG_HOME` on MacOS.

**Describe the solution you'd like**
According to the PR which added config location #150 it uses https://github.com/shibukawa/configdir which simply doesn't take that variable into account.

**Comment by mjarkk** [comment]
But isn't `XDG_CONFIG_HOME` is Linux thing?  
Ya sure you can add those shell variables to MacOS but that doesn't mean we will support them, if that would be so we would also need to support `XDG_CONFIG_HOME` on Windows.  

I also think that this issue has more to do with [shibukawa/configdir](https://github.com/shibukawa/configdir) than with lazygit.  
If you really think this is something important to have on MacOS i would recommend to pass trough the issue to their repo because in that case other programs can also make use of this.

**Comment by cideM** [comment]
Hm good point I'll create the issue in the other repo
