### ISSUE TITLE
How to reset "copied" commits

### ISSUE THREAD

**Issue by peppy** [jesseduffield/lazygit#702]
I'm not sure if there is already a method to do so and I'm missing it, but during an 8-branch rebase I found the need to reset my copied commits several times. The only way I can find to do this is to quit the app right now.

**Comment by jesseduffield** [comment]
You can do this via pressing 'c' on the commit again. If your need is to reset all the copied commits (which are no longer visible) we don't yet have a keybinding for that. Is that your situation?

**Comment by jesseduffield** [comment]
Agreed. Regarding the commits being reset automatically right now, I think what's probably happening is that you're just cherry-picking them again but because the patches are now redundant, they're ignored

**Comment by peppy** [comment]
Aha, yep, that's probably it then!

**Comment by jesseduffield** [comment]
I'd check and see how many commits are loaded (bottom right of commits panel). When we start lazygit we only fetch 30 of them, but after scrolling down far enough (and maybe a couple of other operations) we fetch all of them. After that, it's costly to update the commits panel because we need to re-write all the commits (of which there could be thousands).

I've got an issue up for dealing better with long commit histories, just a matter of getting around to it

**Comment by peppy** [comment]
I see. It goes from 30 to 27028!

**Comment by jesseduffield** [comment]
Yeah haha. Definitely an issue that needs to be fixed properly

**Comment by jesseduffield** [comment]
@peppy I've got a PR up for resetting the commit selection now: https://github.com/jesseduffield/lazygit/pull/714

**Comment by jesseduffield** [comment]
closing as this is now merged
