### ISSUE TITLE
Support undo and redo

### ISSUE THREAD

**Issue by ysmood** [jesseduffield/lazygit#716]
If you have ever used [gitup](https://gitup.co/), the undo and redo is very handy. Hope lazygit can support it.

**Comment by jesseduffield** [comment]
I am not very familiar with gitup. Do they have docs on how what can be un-done? It sounds like a challenging problem to solve

**Comment by ysmood** [comment]
Yes, it is. If you go to the link I mentioned, you can see their screen record for this feature, it's the main reason I still can't switch from gitup to lazygit.

**Comment by jesseduffield** [comment]
I've just played around a bit with it and here are my observations so far:
1) Gitup seems to have had undo-ing in mind from the start: they won't allow for example a soft reset to a previous commit, only a hard reset, and they don't like doing things while the index is 'dirty'. This means they've constricted many operations down to only things that _can_ be undone.
2) In the working tree view on the other hand, it seems like things can't be undone at all, or at least when it tries to it has strange behaviour (adding a bunch of random files I didn't expect to see for example)
3) When you do something irreversible e.g. pushing, it lets you know, and then if you want to undo it will just skip that action and allow you to undo things that came before/after it.
4) When it comes to an interactive rebase (e.g. from trying to move a commit up or down) that has conflicts, hitting undo will take us back to the state before you started the rebase.

So I'm currently thinking, in order to support undoing stuff we need the following: A way to represent actions in a canonical way, and a record of all the actions that are reversible, and how to reverse them. I'm not sure how we would deal with irreversible actions like things that mess with the working tree (e.g. a soft reset) other than copying the entire git repo with every action which I think is infeasible (depending on how big a repo is).

I'm not sure how we would communicate that some things are reversible and others aren't. Perhaps by coloring the text a certain way? Perhaps by giving a warning (I don't really like this idea because there would probably be a lot of warnings).

Either way it would require a big refactor to support, though I do think it's a feature worth investing the time into given how easy it is to accidentally do things wrong in git.

@ysmood do you (or anybody else) have thoughts on this?

**Comment by jesseduffield** [comment]
some more info on how an undo manager is used in swift: https://nshipster.com/nsundomanager/

**Comment by ysmood** [comment]
You think too much. Usually, when we face difficult problems, redo-undo is definitely a very difficult in general, we step back first, most times we don't need the solution to be perfect at the beginning.

From my usage, gitup basically only uses reflogs to do the redo-undo, what it does is very simple, just use it to navigate through reflogs. So the limitations you mentioned are all the limitations of reflogs.

To support it on lazygit, we don't have to refactor the low-level code we already have now.

For the first step, we can support reflogs only, then after users use it, we will find out more ideas and requirements. For me, reflogs is pretty enough for most daily usage.

**Comment by jesseduffield** [comment]
I tested to see whether gitup was just using the reflog and it was not (I linked the NSUndoManager thing they're using above). I do think though that a reflog-based approach would be an easy first start, the only issue being that there may be several reflog entries for a single user interaction. For example an interactive rebase could have many reflog entries even if it was a single user interaction like saying 'rename this commit'. It would take some experimentation to see how far we could go with it.

My current suspicion is that to make it work we'd need to do something similar to what gitup is going right now, which is to maintain the undo stack in state with specifically defined forwards and backwards actions. But I think there's no harm in seeing how far we can go with the reflog approach

**Comment by ysmood** [comment]
Sure, it's not plain reflog, you will find out it after you play around this idea after a while, it's not that complex at all. Git designed this reflog is just for this kind of thing, it's a pretty common design pattern in other software. They just gave it a name that hard to link to redo-undo. I hope lazygit can at least hide the reflog by undo-redo for high-level users.

The main pain to deal with reflog directly, is that I have to read the unfriendly comments it auto-generates. I think this will be the main code for lazygit to handle 😂

**Comment by jesseduffield** [comment]
You make a strong case! I'm having a read through my reflog now and it seems like there's basically three things that happen:
1) we change branches
2) we change commits (by adding, amending, reseting, etc)
3) we do interactive rebases

These should be simple enough to parse (with interactive rebases we can just go to the start of the rebase.

The only real issue comes down to when the user has modified tracked files in their worktree. In that case switching commits can cause conflicts. Do you think we should disallow undoing when there are modified tracked files? Or just try and do the operation and let the user deal with it if there happens to be conflicts?

**Comment by ysmood** [comment]
Let me show you a scenario to make it more clear.

I use gitup to fixup with the keyboard shortcut `F` a lot, when there are a lot of commits to fixup, I may accidentally type more `F` than I want :joy:. When this happens I just type `CMD-Z` to undo it, so that I don't have to touch the unfriendly reflog.

**Comment by ysmood** [comment]
For the conflict. It makes sense to popup an alert to ask the user to stash the current working files before use the undo.

**Comment by ysmood** [comment]
We can collect more users' feedback before we decide how to deal with the conflict, it's not a bottleneck, just some UX optimization for me.

**Comment by jesseduffield** [comment]
sounds good. I'll see what I can whip up

**Comment by jesseduffield** [comment]
@ysmood I've got a PR up for this now if you want to give it a test: https://github.com/jesseduffield/lazygit/pull/718

**Comment by ysmood** [comment]
The code looks ok to me. I also tried the branch with a test repo, work well for basic cases. Good job!
