### ISSUE TITLE
Suggestion: shortcut to interactive rebase on top of selected commit/branch

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#733]
Firstly, thanks for your amazing work on lazygit! ❤️ 

**Is your feature request related to a problem? Please describe.**
lazygit provides lots of shortcuts so you don't have to manually interactive rebase and edit the todo file, but sometimes interactive rebasing is still the best way to go.

For example, if I have some commits that I'd like to re-order, I can use the move up/down shortcuts, but this is very slow (presumably because a rebase is done each time these shortcuts are used).

Another example: I want to rebase a branch on top of another branch and, whilst doing this, I would like to delete some commits which are now included upstream.

When manual interactive rebases are the best way to go, I'd still like to use the lazygit GUI to start the rebase. Otherwise I have to revert to using `git log` to find a commit, copying it, and then typing out the full rebase command.

**Describe the solution you'd like**
I'm not sure what the best solution would be. Firstly I'd like to validate if this is a genuine problem that other people are also experiencing.

**Describe alternatives you've considered**

**Additional context**

**Comment by OliverJAsh** [comment]
Ah, just discovered you can edit the todo file: https://github.com/jesseduffield/lazygit/wiki/Interactive-Rebasing#editing-the-todo-file

However this doesn't help with the second scenario I mentioned:

> Another example: I want to rebase a branch on top of another branch and, whilst doing this, I would like to delete some commits which are now included upstream.

Is there a "lazy" way to achieve that?

**Comment by jesseduffield** [comment]
@OliverJAsh glad to hear you're liking lazygit! Currently it's not possible to start an interactive rebase onto a branch, although it sounds simple enough to implement. am I right in thinking the approach here would be to go `git rebase -i <branchname>` and then set the bottommost pick to 'edit' so that we end up with the same behaviour that we get in lazygit? We could potentially make this something that's possible in a range of contexts e.g. not just the commits panel but also the branches panel, remote branches panel, tags panel, and reflog panel.

**Comment by OliverJAsh** [comment]
> am I right in thinking the approach here would be to go `git rebase -i <branchname>` and then set the bottommost pick to 'edit' so that we end up with the same behaviour that we get in lazygit?

Yeah I believe so. That would be great.

Sometimes I also want to rebase on top of a specific commit that lives on another branch. I'm not sure how that workflow would fit into lazygit 🤔

**Comment by jesseduffield** [comment]
In another issue somebody brought up a similar thing. I think the right move there is to allow you to press 'enter' on a branch and see the branch's commits within the same panel, similar to how you can press enter on a commit and see the commit's files in the same panel. I don't think it should be too hard to implement, just a matter of getting around to it.

**Comment by jesseduffield** [comment]
I have since gotten around to allowing users to view the commits within a branch, so this issue is closer to being resovlved

**Comment by lawrence-laz** [comment]
I see this task has `usability` label, does this mean there is some way to interactively rebase onto another branch? If so, how? I need this for this scenario:
> Another example: I want to rebase a branch on top of another branch and, whilst doing this, I would like to delete some commits which are now included upstream.

**Comment by jesseduffield** [comment]
@lawrence-laz that label just means that this is an issue relating to usability, as opposed to suggesting that this is issue is the result of a knowledge/documentation gap.

Nonetheless this issue should be simple enough to implement, so I'll chuck a good-first-issue label on it.

If anybody wants to tackle this, it's a matter of swapping out the existing confirmation popup from the 'r' keybinding in the branches panel for a menu where one option is to directly rebase and the other is to begin an interactive rebase so that you can edit the TODO file. Upon selecting the section option we would then need to invoke the interactive rebase but with the 'edit' action on the base commit so that the user can go in and make changes to the TODO file before continuing. `pkg/commands/git_commands/rebase.go` is where most of the changes would be made. We'd want a method in there that takes two commits (e.g. current HEAD and the head of the branch we're rebasing onto) and returns a TODO file with the base commit in an edit state). Then we'd probably expand `PrepareInteractiveRebaseCommand` to handle the new kind of rebase.

**Comment by AzraelSec** [comment]
I'm jumping aboard 👋🏻 First of all, I've recently started using lazygit and it seems really cool. Nice work!

The ability to perform an interactive rebase editing the TODO file on the fly is absolutely vital to me. I don't see any assignee on this issue, would it be okay with you @jesseduffield if I take care of it?

**Comment by jesseduffield** [comment]
Go right ahead @AzraelSec !

**Comment by joihn** [comment]
the desired feature can be achieved via a custom command:
https://github.com/jesseduffield/lazygit/issues/2517#issuecomment-1487130099

**Comment by OliverJAsh** [comment]
Closed by https://github.com/jesseduffield/lazygit/pull/2370
