### ISSUE TITLE
custom alias in my ~/.zshrc isn't working with the lazygit's custom command option ':'

### ISSUE THREAD

**Issue by akbarsha03** [jesseduffield/lazygit#770]
**Description**
When I try to run the custom command using lazygit's ':' option, it doesn't run any of my alias given in the ~/.zshrc

**Steps to reproduce the behavior:**
1. Go to lazygit
2. Enter custom command using ':' mode
3. Enter an alias from your ~/.zshrc (in my case, the alias is `alias gitlfs="git lfs install && git lfs pull && git lfs uninstall && git reset ."`)
4. You'll notice "bash -c gitlfs" command not found

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Lazygit Version: 0.18, os=darwin, arch=amd64

Thanks

**Comment by glvr182** [comment]
This is because we call the shell directly, note that when in a terminal the command `zsh -c l` also does not work since it does not use the zshrc file. 
I have not found a way to force the zsh command to use the zshrc file. But we would have to either source the zshrc file ourself, or find an argument to automaticly do that.

**Comment by jesseduffield** [comment]
Yeah I'm not too sure how to get around this one

**Comment by AckslD** [comment]
@glvr182 @jesseduffield 
Couldn't $SHELL be used such that `zsh -c` is called instead of `bash -c` if this is the default shell on the users system?

Regarding aliases in `zsh -c`, they will work if you put them in `.zshenv`.

**Comment by crates51** [comment]
I used kinda a hacky workaround for this(or at least something like this)

i had a function in .zshrc called gitlab_deploy which also gave me 

```
+ bash -c gitlab_deploy
                                                                       
bash: gitlab_deploy: command not found
```
when running with ctrl+d from lazygit (d from deploy, get it? hah)

what i did is to move the script from .zshrc to one folder from $PATH variable (i chosed /home/<name>/bin)

and then in my lazygit/config.yml:
i moved from 
`command: 'gitlab_deploy'`
to
`command: 'zsh -c gitlab_deploy'
`
so in the end it will execute `bash -c "zsh -c gitlab_deploy"` instead of `bash -c gitlab_deploy`

**Comment by Saafo** [comment]
Seems this bug appears again in 0.49.0

**Comment by stefanhaller** [comment]
@Saafo You should have seen a "breaking changes" popup when first starting the 0.49 version of lazygit, explaining the change with a [link to the documentation](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#using-aliases-or-functions-in-shell-commands) that explains the situation. Let me know if you didn't see this (you don't if you build from source), we might have a bug there.

If there are still questions open after reading that documentation, we may have to improve the wording.
