### ISSUE TITLE
In some terminal the selected line (file / branch / commit) is blinking

### ISSUE THREAD

**Issue by sebi88** [jesseduffield/lazygit#840]
From the new version, the selected file / branch / commit is not just bold, but it's blinking. It gets too much attention.

**Lazygit version:**  0.20.3
**Linux version:** Linux Mint 19.3 Tricia

**Comment by jesseduffield** [comment]
That's interesting, on my end it's simply bolded. In other terminal applications when you see bold text, do they also blink? I wonder if part of this could also come down to the fact that we're applying the bold attribute to the background and not just the foreground.

I would see what happens when changing the selected background colour to this:
```
  gui:
    theme:
      selectedLineBgColor:
```
That is: have no items under `selectedLineBgColor`

**Comment by sebi88** [comment]
Thx for the answer!

Empty `selectedLineBgColor` doesn't work, it throws an exception:
```
ERROR 2020/05/15 10:52:47 svType != tvType; key=selectedlinebgcolor, st=<nil>, tt=[]interface {}, sv=<nil>, tv=[bold]
```

but this one
```yaml
gui:
    theme:
      selectedLineBgColor:
      - default
```
 solves the blinking!

My default terminal **xfce4-terminal 0.8.7.4**, the  problem is the same in  **gnome-terminal 3.28.1**

**Comment by jesseduffield** [comment]
I've changed this to the default behaviour so that nobody else trips on this issue :)

**Comment by sebi88** [comment]
thx :pray:
