### ISSUE TITLE
emojis consume next character

### ISSUE THREAD

**Issue by fiendish** [jesseduffield/lazygit#88]
(was originally just about commit messages, but it looks like it's not just those)

The next character (byte?) after any emoji appears to be consumed.

"🔊logging" will display as "🔊ogging"

If you need a repo to test this on, the gitmoji repo uses them all over the place. https://github.com/carloscuesta/gitmoji

[edit again] Probably related to the chinese character display issue in https://github.com/jesseduffield/lazygit/issues/24

**Comment by fiendish** [comment]
If you need a repo to test this on, the gitmoji repo uses them all over the place. https://github.com/carloscuesta/gitmoji

**Comment by jesseduffield** [comment]
This should be fixed by https://github.com/jesseduffield/lazygit/pull/231

I tested on that repo and there was some weirdness but the issue with '🔊logging' is resolved. If you come across more issues please report them https://github.com/jesseduffield/lazygit/issues/24 as I'll make that issue the main unicode/emoji issue to track this stuff :)
