### ISSUE TITLE
Option to change refresh rate/frequency

### ISSUE THREAD

**Issue by OliverJAsh** [jesseduffield/lazygit#894]
**Is your feature request related to a problem? Please describe.**
I find myself having to manually refresh too often. I would like lazygit to refresh automatically more frequently.

**Describe the solution you'd like**
An option to change to refresh rate/frequency.

**Describe alternatives you've considered**

**Additional context**

**Comment by jesseduffield** [comment]
For anybody who might want to tackle this, we currently refresh files/submodules every 10 seconds, and we re-fetch every 60 seconds. These could be made into configurable times. They're currently hardcoded in `pkg/gui/gui.go` where we call `gui.goEvery`. The place to create new config keys would be `pkg/config/user_config.go` and you'd also want to update the docs in `docs/Config.md`.

Worth noting that I tried getting file watching working again recently but couldn't find a way around the issue where you get an error due to too many files being watched.

**Comment by Liberatys** [comment]
If I'm not mistaken this should have been addressed by my pull request some months ago? @OliverJAsh Can you check? :D
