### ISSUE TITLE
Ability to use existing shell for commands and git actions

### ISSUE THREAD

**Issue by lordlycastle** [jesseduffield/lazygit#899]
**Is your feature request related to a problem? Please describe.**
If you have a git hook before push/commit and it depends on a certain tool e.g. node then it is best to use the current shell.

For example I have `nvm` and various node versions. In the git hook it runs tests using node and it expects a certain version. I load the correct version by `nvm use v8` but lazygit still complains about wrong version and stops all the commits and pushes. That is because I image it is running in a separate shell like when you run custom commands, and in that shell `nvm` never switched to required version.

This is the same issue when you run custom commands, it runs `bash -c ...`. Firstly now you need to format your commands for bash instead of default shell/current shell which is very annoying (especially for `fish` users where syntax is different). And you cannot use local variables, and some time even all commands as you might not have updated `.bashrc` to include all paths that are there in your current/default shell; since you never use it.

**Describe the solution you'd like**
Run all custom commands and git commands in current shell process.

**Describe alternatives you've considered**
Alternative is using `git` directly from current shell and not using `lazygit`.

**Comment by jesseduffield** [comment]
I think we can get halfway there by letting the user specify which shell to use. It means you won't have access to local variables but you'll get access to your rc file for example

**Comment by lordlycastle** [comment]
I wonder if that'll work with `nvm` because you need to do `nvm use` but it would certainly be a good step forward to be able to specify a shell. The shells can be hooks like you say to do these actions before running the custom command. This would be a good feature regardless! 💯

It is the hooks that need the custom environment. We chose not to include `nvm use` etc. in hooks because people use different tools to manager versions. This is sadly true for most other languages. So it is on the user to "be" in the right env for the git hooks. 

Can we maybe use the same shell for all custom command and hooks? Because then user can do it normally in two commands e.g. `nvm use` and then `Commit` action that will run the hooks' tests in same shell which is using the correct version of tool 🤔 ... totally a random idea.

**Comment by PeterPCardenas** [comment]
Wanting this too, `fish` will automatically source the config on restart, so as long as the variables are set there should be ok?

**Comment by GeorgiChochev** [comment]
Bump

I'd be happy with the proposal from @lordlycastle Lazygit using the shell it was launched from

**Comment by stefanhaller** [comment]
Fixed by #3793.

**Comment by NeaGogu** [comment]
Hello. I have stumbled upon this thread when I was trying to make lazygit open the file in neovim (which is aliased in my .zshrc file). I built the project from source because I saw that the last release was pretty old. My default shell is zsh, and I also added logs in the code here: https://github.com/jesseduffield/lazygit/blob/05ae0800c3ff3fd7160a5705a8fbac7f50745624/pkg/commands/oscommands/os_default_platform.go#L23-L28

and the correct shell is logged, but the command still uses bash. 
![image](https://github.com/user-attachments/assets/69ba8d0a-c991-41bb-928c-c929801e2d00)

As a workaround I've changed the edit command with the full path to nvim in the config file, but I'd like to make this work. I'd appreciate it if someone could help me 🙏

**Comment by NeaGogu** [comment]
Oh.
> I wouldn't call that a workaround, this seems like the appropriate solution to me. What's wrong with it?

Nothing wrong necessarily but I was hoping I could force lazygit to use zsh and load my .zshrc when using commands such as edit. I share my configs with my linux machine as well and wanted to use the alias for nvim instead of hardcoding the full path to the binary.

**Comment by PeterCardenas** [comment]
@NeaGogu  if you export the `PATH` variable, it should get picked up. for fish i do `fish_add_path -P ...` and it gets picked up

**Comment by stefanhaller** [comment]
@lordlycastle @peter-cardenas-ai @PeterCardenas @GeorgiChochev This was fixed in #3793, but we are now considering reverting that PR because it creates problems. We are proposing to do #4385 instead, which requires a bit of setup work for users. Please give your feedback on whether you think this is a viable approach.

**Comment by PeterCardenas** [comment]
i have since worked around this limitation by adding directly to PATH so that sub processes can call commands, and have moved my fish functions for clipboard copy and edit to a directory in my PATH. i would still prefer interactive for simplicity but this could also work so that i can source specific functions while keeping them in the fish functions directory for performance. i will say it's a bit non-intuitive that these functions aren't available. that is, people are going to run into the issue of the function not being available, and most likely will hack it so that it's available in noninteractive mode always like I did

**Comment by stefanhaller** [comment]
@PeterCardenas As a fish user you won't have to do anything. If I'm not mistaken, then `~/.config/fish/config.fish` is sourced for both interactive and non-interactive shells, so all you have to do is make sure that your function definitions are outside of the `if status is-interactive` condition in that file, and then it will just work.

**Comment by PeterCardenas** [comment]
hmm i was referencing putting my function in `~/.config/fish/functions` to be [autoloaded](https://fishshell.com/docs/current/language.html#syntax-function-autoloading), but it appears these are available in non-interactive mode as well! lgtm then, can't speak for other shells tho
